- README.md
- aleph/ingest/tesseract.py
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs links for their .org -> .io migration for hosted projects

- .travis.yml
- aleph/core.py
- aleph/default_settings.py
- aleph/oauth.py
- aleph/static/js/controllers/AppCtrl.js
- aleph/static/js/controllers/SessionCtrl.js
- aleph/static/style/_session.scss
- aleph/static/style/aleph.scss
- aleph/static/templates/login.html
- aleph/tests/util.py
- aleph/views/sessions_api.py
- contrib/docker_settings.py
This updates the OAUTH support to handle multiple providers. The login endpoint changes to `/api/1/sessions/login/<provider>` and the callback URL changes similarly. There is built-in support for Facebook and Google, and it's very easy to add support for other providers.
NB: the callback URL entered into the Google Developer Console must be updated.
When the user clicks the login dialog they get a modal popup giving them a choice of login providers.
This doesn't yet include full support for Twitter, because I don't yet have a functioning Twitter OAUTH setup.
> Support for multiple OAUTH providers

- .travis.yml
- Makefile
- aleph/migrate/versions/2d230e6ce46d_added_credentials.py
- aleph/model/__init__.py
- aleph/model/common.py
- aleph/model/credential.py
- aleph/model/role.py
- aleph/tests/factories/models/__init__.py
- aleph/tests/factories/models/credential.py
- aleph/tests/factories/models/role.py
- aleph/tests/test_credential_model.py
- aleph/tests/test_models.py
- aleph/tests/test_role_model.py
- aleph/tests/test_sessions_api.py
- aleph/tests/test_view_util.py
- aleph/views/sessions_api.py
- aleph/views/util.py
Split some of the existing role data into credentials model.
This layout and authentication mechanism should be flexible enough for us to pull-in additional authentication _protocols_ (LDAP is a good example, #52).
I'll prepare a separate PR for the front-end functionality.
@longhotsummer if you have a minute, it would be great to have your :eyes: on this and let us know how these changes will work for you.
@pudo from #52 I understand we want user registration to be optional?
> Credentials

- Dockerfile
- Makefile
- requirements.txt
This should fix #135 and partially #130 (the `node_modules` part).
Particularly the issue was caused by the fact that node installs modules inside the mountable path (`/aleph` itself). This should be fixed now.
Regarding the #135, to test it please run the command against the upstream Docker image:
```bash
docker run -t -i pudo/aleph python -c "import pkg_resources; print list(pkg_resources.iter_entry_points('aleph.ingestors'))"
```
/cc @olethanh @sihil
> Setup fixes

- aleph/metadata/__init__.py
This is useful when we've changed the metadata not to have some fields, but code still checks for them.
> Guard against not have a metadata field at all

- aleph/core.py
This also takes into account that Celery now wants its options to be lowercase, whereas the old `celery.conf.update(app.config)` gave it way too much info and tended to use uppercase.
> Allow overriding celery options from config file

- aleph/model/role.py
- aleph/static/js/aleph.js
- aleph/static/js/controllers/SignupCtrl.js
- aleph/static/js/services/Role.js
- aleph/static/templates/signup.html
- aleph/tests/test_roles_api.py
- aleph/views/base_api.py
- aleph/views/roles_api.py
- requirements.txt
This branch provides UI for password login and registration (wip). #52 (previously stas/aleph#1)
Ideally, I would merge this into the `credentials` branch after a quick review to keep the branches as small as possible for review.
General login UI (options dynamically disappear if disabled, say registration)
Email login UI
> Credentials ui

- Makefile
This should provide a fix for #163.
Basically, we should always make sure the package is installed in development mode. 
Production configuration should not be affected.
> Make sure we generate the egg-info in development mode.

- README.rst
This is just a pet peeve of mine.
> GitHub has a capital H

- aleph/tests/test_roles_api.py
- aleph/views/roles_api.py
Was investigating using Aleph and wanted to use email and password signup rather than Oauth, I couldn't get the signup process to work. The user role would never end up in the database for the next session.
I think the current test  `RolesApiTestCase.test_create_success` passes because the database session is still around from which to retrieve the role from, but if this session is closed, as would happen for a new request, the role won't have been committed to the database yet.
I've included a change to the test to illustrate this and a fix in the API view.
I'm new to Aleph so maybe I've missed/overlooked something here, feedback welcome, maybe I'm just not doing something right.
Cheers!
> Role password signup fixes

- aleph/core.py
- aleph/views/base_api.py
- aleph/views/util.py
oauth: require same host, but not same port
password login: use relative urls
> 	jwt auth compatibility for standalone ui running on a different port

- aleph/tests/test_view_util.py
- aleph/views/sessions_api.py
- aleph/views/util.py
OAuth2 [only supports](https://auth0.com/docs/protocols/oauth2/oauth-state) the `state` parameter for passing custom state, so this PR moves the next URL to the state.
It also fixes the next URL extraction. Currently `extract_next_url` will always default to returning the request referrer as it tests this after the `next` query parameter. I've made one of the tests set a referrer to show this happening.
The PR adds a new method, `get_best_next_url` that you pass any number of URLs to and the first safe URL is returned, or the app URL. Given that we can no longer assume the next URL will be in the `next` query parameter this seems like a nicer, more general method. I've left `extract_next_url` in the codebase for comparison purposes, but I think it should be removed before this PR is …
> Fix oauth next URL

- aleph/search/parser.py
- aleph/search/query.py
- aleph/tests/test_search_api.py
- aleph/tests/test_search_parser.py
- aleph/tests/test_search_query.py
This PR adds the `post_filter` param and makes all filters OR by default.
Fields flagged as `MULTI_FIELDS` already used OR logic, given that a non-multi field can never match more than one value, it seems more sensible that it follows the same convention. This means we can remove the `MULTI_FIELDS` distinction in favour of more predictable API behaviour.
---
The `post_filter` parameter filters the results **after** aggregations.
For example, given the following API calls:
```
/search?facet:collection_id&filter:collection_id=5
/search?facet:collection_id&post_filter:collection_id=5
```
Both will return the same set of results, but in the former there will only be one entry in the `collection_id` facet (for `collection_id = 5`), while in the latter there will be a full `collection_id` …
> Add post_filter to API and make OR default

- aleph/index/__init__.py
- aleph/index/admin.py
- aleph/index/collections.py
- aleph/index/core.py
- aleph/index/documents.py
- aleph/index/entities.py
- aleph/index/mapping.py
- aleph/index/records.py
- aleph/index/stats.py
- aleph/index/util.py
- aleph/logic/collections.py
- aleph/logic/xref.py
- aleph/search/__init__.py
- aleph/search/query.py
- aleph/tests/test_base_api.py
- aleph/tests/test_index.py
- aleph/views/serializers.py
- docker-compose.dev.yml
- docker-compose.prod.yml
- requirements.txt
Last night, ES 6 came out. There's now a plan to abandon support for doc_types, i.e. there can be only one mapping per index. I've decided that the easiest way to work around that is to have multiple indexes: one for documents and entities, one for collections and one for records.
In this refactor, I've also introduced the option to write to one index and potentially query another, as discussed in #244. This should make future mapping migrations more flexible.
> Support ElasticSearch 6.0.0

- .dockerignore
- Dockerfile
- Makefile
- aleph/default_settings.py
- aleph/index/documents.py
- aleph/index/entities.py
- aleph/index/mapping.py
- aleph/ingest/result.py
- aleph/logic/__init__.py
- aleph/logic/collections.py
- aleph/logic/entities.py
- aleph/manage.py
- aleph/model/collection.py
- aleph/model/common.py
- aleph/model/document.py
- aleph/model/entity.py
- aleph/model/metadata.py
- aleph/search/__init__.py
- aleph/tests/test_entities.py
- aleph/tests/test_entities_api.py
- aleph/tests/test_xref.py
- aleph/tests/util.py
- aleph/views/documents_api.py
- aleph/views/entities_api.py
- aleph/views/serializers.py
- contrib/devwrapper.sh
- docker-compose.dev.yml
- docker-compose.prod.yml
- requirements.txt
- setup.py
This makes API-created entities behave like bulk-loaded ones, in that they will have many values for each property (e.g. aliases, addresses, phone numbers, birthdates). I still worry that this will make the UI a little harder, but it gets lots of bonus points for consistency.
> Make all entity properties into lists

- ui/src/components/DocumentScreen/DocumentContent.jsx
- ui/src/components/DocumentScreen/DocumentInfo.jsx
- ui/src/components/DocumentScreen/DocumentToolbar.jsx
- ui/src/components/DocumentScreen/DocumentToolbar.scss
Just a PR to confirm the DocumentToolbar - a consistent toolbar for all Document views where we can put actions scoped to a document - is heading in the right direction.
1. The Download button works.
2. The DownloadButton component also accepts an array (where it makes sense to have multiple download options - such as for emails with attachments or MS Office Documents with both native versions and PDF versions) but this is not used _yet_.
3. The "Search in document" control is there as a placeholder but is disabled and not wired up.
> Adding Toolbar to Document view

- ui/README.md
- ui/package.json
- ui/src/app/App.jsx
- ui/src/components/DocumentScreen/DocumentCollection.jsx
- ui/src/components/DocumentScreen/DocumentContent.jsx
- ui/src/components/DocumentScreen/DocumentInfo.jsx
- ui/src/components/DocumentScreen/DocumentInfo.scss
- ui/src/components/DocumentScreen/DocumentMetadata.jsx
- ui/src/components/DocumentScreen/DocumentRelatedScreen.jsx
- ui/src/components/DocumentScreen/DocumentToolbar.jsx
- ui/src/components/EntityScreen/EntityContent.jsx
- ui/src/components/EntityScreen/EntityContent.scss
- ui/src/components/EntityScreen/EntityInfo.jsx
- ui/src/components/EntityScreen/EntityInfo.scss
- ui/src/components/EntityScreen/EntityInfoTags.jsx
- ui/src/components/EntityScreen/EntityReferencesTable.jsx
- ui/src/components/EntityScreen/EntityRelatedScreen.jsx
- ui/src/components/EntityScreen/index.jsx
- ui/src/components/common/Collection/CollectionInfo.jsx
1. Entity view now looks like document view with metadata on the right.
2. Entity and Document "related" view now also render with metadata on the right. 
3. There is a new tabbed info sidebar which structures the file metadata much better.
4. The entity pages are a very rough "in progress" version but with no loss of functionality. We have a template to improve them but have not worked on it yet.
5. File search now only works in folder or email view (disabled on a file, as that doesn't exist yet).
With regard to the Entity and Document "related" screens (e.g. https://beta.data.occrp.org/entities/{id}/related) clicking a related tag in the sidebar should take to a search view, and we will remove the "related" screens in future.
The only places there are panels on the left are:
1. The …
> Entity View and Document View now consistent

- ui/src/components/Facet/SearchFacet.jsx
- ui/src/components/Facet/SearchFacet.scss
- ui/src/screens/DocumentScreen/DocumentInfo.jsx
- ui/src/screens/HomeScreen/HomeScreen.jsx
- ui/src/screens/HomeScreen/HomeScreen.scss
* Now only fetches facet counts if facet menu is open for a significant performance improvement.
* Now displays the Open button on DocumentInfo toolbar when a  preview is open in non-maximised mode.
* Removed the ‘Browse sources’ button from the homepage by request.
> Facet Counts, DocumentInfo toolbar, Homepage

- aleph/settings.py
If one is setting up OAuth and do not fill out all settings, a user might get redirected to Google login instead. It is better that users make sure that they have their aleph.env setup correctly than assume that the default values are correct for their use case.
https://github.com/alephdata/aleph/wiki/System-configuration should also be updated to document that there are multiple providers available.
> Remove default OAuth settings

- aleph/index/entities.py
- aleph/index/util.py
- aleph/logic/entities/__init__.py
- aleph/logic/entities/bulk.py
- aleph/tests/test_collections_api.py
- aleph/tests/test_entities_api.py
- aleph/views/collections_api.py
This is an API suggested in conversation with @Ueland - for writing bulk entities using the REST API. Here's the mechanism:
``POST /api/2/collections/453/_bulk``
The expected body is a JSON array of FollowTheMoney entities with the following fields: 
* ``id`` - an ID, unique to the current collection (best practice is to put the collections foreign_id) into key values as a SHA1.
* ``schema`` - name of an FTM schema, e.g. ``LegalEntity``.
* ``properties`` - a dict with property values
> Bulk indexing API

- platform/elasticsearch/Dockerfile
Latest version - https://www.elastic.co/guide/en/elasticsearch/reference/6.5/release-notes-6.5.2.html
> Update Elastic to 6.5.2

- ui/src/components/SearchAlert/SearchAlert.jsx
- ui/src/components/SuggestAlert/SuggestAlert.js
- ui/src/components/common/ErrorSection.jsx
- ui/src/screens/SearchScreen/SearchScreen.jsx
>4. [Search Screen] Do not show empty pages like "No search result" or "This folder is empty"(for Cases) instead offer users to "Set an Alert" and "Upload files"
This PR partially **for search** implements 4) point from #513 issue, the part  **for cases** will not be implemented for next version.
In cases where there is no search result matching to query users will be suggested to set an alert for the term, if an alert already set for the term suggestion will not appear.
> Non ideal state suggestion

- ui/src/components/Collection/CollectionToolbar.jsx
The issue was reproducible only in `data.occrp.org`
When the user clicks on `Manage...` button in the collection page
then the whole app crashes into a white page.
Debugging showed `Menu.Item` variable as `undefined` which supposed to be an alias for `MenuItem` component `blueprint@3.x.x`. Most probably this is because of missing `package-lock.json` file.
Instead of using `Menu.Item` alias use `MenuItem` component directly.
I think event we have a fix for now but we still shall dig deeper into this issue to find the origins.
Big thanks to @uhhhuh for reporting about the bug
> [Hotfix] Collection toolbar critical bug

- services/elasticsearch/k8s-entrypoint.sh
Currently if the secrets directory is empty (as is the case with a brand-new installation), elasticsearch crashes because it is passed a literal asterisk with `elasticsearch-keystore add-file * /secrets/*`.
Desired behavior is to either call elasticsearch-keystore with each keyfile (like `elasticsearch-keystore add-file foo /secrets/foo`), or, if there are no keyfiles, to not call `elasticsearch-keystore add-file` at all.
This change skips the for-loop if the secrets directory is empty.
> Ignore empty directories

- ui/src/components/Collection/CollectionStatus.jsx
- ui/src/components/Document/DocumentManager.jsx
fetch collection status: call next fetch after the previous one finished to avoid a pile of unfinished requests in case the server is unable to respond in 2 or 6 seconds
> improve status update timeouts

- ui/src/components/Document/DocumentViewMode.jsx
- ui/src/components/Entity/EntityViews.jsx
@pudo I was able to reproduce this issue in production, but not locally (even with the same invalid test file)
Based on what I observed in the network requests in production, this fix should display the appropriate processing error message if there is one and hide the mentions tab in that case, but I'd appreciate your double check that the logic is sound :)
> Handle processing errors in document view mode

- ui/package.json
Replaces deprecated react-intl-cra packege with formatjs's internal cli command to extract messages and output to json file
Resolves #901
> Replace react-intl-cra

- aleph/logic/mapping.py
- aleph/tests/test_mappings_api.py
- aleph/validation/schema/mapping.yml
- aleph/views/mappings_api.py
- aleph/views/serializers.py
cc @kjacks 
Some notes:
- The `csv_url` in the generated mapping yaml is a signed Google Storage URL and it expires after a while (24 hours by default). So the mapping when run with ftm cli will not work after that period.
- When used in dev mode, local filesystem is used for blob storage. So the csv_url is a file path inside the container. So if the user wants to run the mapping with ftm cli, they'll have to do it inside a container (`make shell` will give you one)
- I'm not quite sure about the return type. Should I directly return the yaml content or should I return it as json? or is it fine as it is?
- Also, the only additional data the endpoint is returning is the signed url for the csv file. May be if we include that in the mapping view response, we won't need a separate endpoint …
> Include table csv link in serialized mapping object

- ui/package.json
- ui/src/components/Diagram/DiagramEditor.jsx
- throttles autocomplete entity query request
- deletion of entities no longer cascades to delete from collection
- prevents creation of vertices with empty caption in vertex create dialog
- improves error-catching in vertex create dialog createEntity request
Outstanding issue: entities added to network diagrams have their `proof` property populated with a reference to their source document entity in Aleph. This creates a dangling entity reference, unless vislib automatically creates a `Document` entity for this source document, which seems less than ideal.
Vislib could hide/ignore properties with 'Document' range, but this would probably necessitate a change to FTM...
> Entity suggest tweaks

- requirements.txt
- services/ingest-file/ingestors/cli.py
- services/ingest-file/ingestors/settings.py
- services/ingest-file/ingestors/support/cache.py
- services/ingest-file/ingestors/support/convert.py
- services/ingest-file/ingestors/support/ocr.py
- services/ingest-file/requirements.txt
We want this to be long-lived and stable. This would store the ingest cache in the same database as the FTM_STORE. It's a bit messy, but better than having yet another piece of infrastructure flying around.
> Use SQL database to cache OCR/doc-conv results

- aleph/index/util.py
- aleph/search/facet.py
- aleph/search/parser.py
- aleph/search/query.py
- aleph/tests/test_base_api.py
- aleph/tests/test_search_api.py
- aleph/tests/test_search_query.py
- aleph/tests/test_stream_api.py
- aleph/tests/util.py
fixes #721 
The url looks like `/entities?filter:schema=Message&filter:gte:properties.date=2018-03-01&filter:lte:properties.date=2018-03-05&facet=properties.date&facet_interval:properties.date=day`
Uses `date_histogram` aggregation with (calendar intervals)[https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html#calendar_intervals] for faceting. So we can facet on minutes up to years.
> Filter and facet on date values

- aleph/logic/documents.py
- aleph/tests/test_ingest.py
for the `aleph crawldir` shell command: don't create an initial root folder as parent to be consistent with the behaviour of `alephclient crawldir`
> Don't create intial root folder in shell crawldir command

- Makefile
- aleph/core.py
- aleph/settings.py
- docker-compose.dev.yml
This pull request adds a `ALEPH_PROFILE` env flag that enables the werkzeug profiler middleware. This is useful for finding slow portions of the code and understanding the code-paths associated with various API requests.
> Added API Profiling

- aleph/oauth.py
- setup.py
Adds option for using Active Directory Federation Services directly as the OAuth 2 provider
> Add ADFS as OAuth option

- aleph/index/util.py
- aleph/search/query.py
- aleph/tests/test_search_api.py
- aleph/tests/util.py
Grouping all conditions in a single query prevents ES from
considering entities with multiple date values that match one of
the individual conditions separately but not all the conditions at
once.
> When filtering dates, put all filters for a field in a single range query

- aleph/model/common.py
- aleph/model/entityset.py
- aleph/model/role.py
- aleph/tests/test_entitysets_api.py
- aleph/validation/schema/entity.yml
- aleph/validation/schema/entityset.yml
- aleph/views/entitysets_api.py
- aleph/views/serializers.py
- aleph/views/util.py
This expands the entity set API like this:
* `GET /api/2/entitysets/YADA/items` - returns a database-backed, paginated index of the entity set items, including judgement and authorship metadata
* `POST /api/2/entitysets/YADA/items` - lets you create or update one item, for example to modify the judgement. If the judgement is set to `no_judgement`, that implements item deletion. (is that too weird??)
* `GET /api/2/entitysets/YADA/entities` - returns a search-backed entities endpoint for search on all items with judgement `positive`. 
* `POST /api/2/entitysets/YADA/entities` - this is where it gets weird. This actually implements full entity upsert, but the entities added here will be added to the entity set, too. 
I haven't currently implemented an explicit `DELETE` API. Deletion can be …
> Expand entityset API

- .gitattributes
This allows the elasticsearch container to start on Windows. Without this fix, it fails on startup due to k8s-entrypoint.sh having Windows-style line endings (which the bash running in the container doesn't understand). 
Most of the project then seems to run fine (including the API), except for the UI which "fails to compile".
> Fix for Docker on Windows

- ui/src/components/Notification/NotificationList.jsx
- ui/src/components/Notification/NotificationListFilter.jsx
- ui/src/components/common/ExportLink.jsx
- ui/src/screens/NotificationsScreen/NotificationsScreen.jsx
Resolves #1286 
@pudo The only remaining issue is that there are two separate event types for the creation of lists and diagrams, but the notification events aren't tagged separately, so both types appear under "New list"
> Notifications list event filter

- ui/src/components/Document/DocumentDropzone.jsx
- ui/src/components/Document/DocumentDropzone.scss
- ui/src/components/Screen/Screen.scss
upload: dropzone now covers the whole screen, only excluding navbar and breadcrumb
changes `<main>` css display property from `block` to `flex`!
before:
after:
> Upload: Larger Dropzone

- ui/src/dialogs/DocumentUploadDialog/DocumentUploadView.jsx
- ui/src/dialogs/DocumentUploadDialog/DocumentUploadView.scss
- Limit height of file list to max 60% height of viewport. Before the user had to scroll down the complete list in order to submit the form.
- add simple stats: number of selected files, total upload size of all selected files
before
after
> Upload: Improve preview screen

- ui/src/dialogs/DocumentUploadDialog/DocumentUploadDialog.jsx
- ui/src/dialogs/DocumentUploadDialog/DocumentUploadStatus.jsx
Calculate progress bar value based on uploaded bytes per file versus total size to upload
Before this change the progress bar went forward as soon as the request for a file started. Most of the time the progress bar therefore just showed 100% even when a lot of upload requests were still going on.
> Upload: Track progress of each request

- ui/src/actions/documentActions.js
- ui/src/dialogs/DocumentUploadDialog/DocumentUploadActionsDone.jsx
- ui/src/dialogs/DocumentUploadDialog/DocumentUploadActionsPending.jsx
- ui/src/dialogs/DocumentUploadDialog/DocumentUploadDialog.jsx
- ui/src/dialogs/DocumentUploadDialog/DocumentUploadStatus.jsx
- ui/src/dialogs/DocumentUploadDialog/DocumentUploadStatus.scss
- ui/src/dialogs/DocumentUploadDialog/DocumentUploadTrace.jsx
- don't close dialog on errors
- show user the amount of failed file uploads
- detailed upload status per file as a scrollable list
- retry function: re-upload all files where an error occurred
- while upload is running: add cancel button, prevent dialog from being closed by hitting esc
- cancel post requests when dialog is closed
While uploading:
When errors occurred:
No errors:
> Upload: Error handling

- ui/package.json
- ui/src/components/Screen/Screen.jsx
- ui/src/components/Screen/ScreenBase.jsx
Wraps Aleph Screen component to allow us to use blueprint's default HotkeysTarget instead of hackily importing from the blueprint esnext build
Solves ui build issue in #1390
> Remove blueprint esnext node modules direct import

- ui/src/components/Entity/EntityReferencesMode.jsx
I am a bit unsure about this fix. For the devired entities mode, it fixes the issue of not showing entities names
but I saw in other places that you are using `entity.getProperty(prop)` instead of `prop.name` as well... :thinking:
> Display derived entities properly in EntityReferencesMode

- aleph/model/entityset.py
- aleph/views/entitysets_api.py
Even if a user has read access to an `EntitySet`, they may not have read access to all of the `EntitySetItem`s within that set. This PR uses `authz` to filter out those items so that they don't get leaked to the user.
This leaking will still be an issue until #1428 is resolved.
> Added authz to EntitySet.items() so we don't leak entities

- aleph/logic/entitysets.py
- aleph/logic/profiles.py
- aleph/model/entityset.py
- aleph/tests/test_entitysets_api.py
- aleph/views/entities_api.py
This adds a new endpoint attached to entities in order to find all EntitySets which reference the entity. The entitysets can be filtered based on type, collection_id, label or the judgement on the entity within the set.
> GET /entities/<entity_id>/entitysets Endpoint

- ui/package.json
- ui/src/components/Diagram/DiagramEditor.jsx
- ui/src/components/Entity/EntityActionBar.jsx
- ui/src/components/Entity/EntityActionBar.scss
- ui/src/components/Entity/entityEditorWrapper.jsx
- ui/src/components/EntityTable/EntityTable.jsx
- ui/src/components/EntityTable/EntityTable.scss
- ui/src/components/EntityTable/EntityTableViews.jsx
- ui/src/components/common/Breadcrumbs.jsx
- ui/src/components/common/UpdateStatus.jsx
- ui/src/components/common/index.jsx
- ui/src/screens/EntitySetIndexScreen/EntitySetIndexScreen.jsx
- ui/src/screens/EntitySetScreens/DiagramScreen.jsx
- ui/src/screens/NotificationsScreen/NotificationsScreen.jsx
- ui/src/util/updateStates.js
Fixes #1477 
Fixes #1474 
Re: #1478 
I still wasn't able to reproduce this issue with saving entity props, but I added a status tag to the table editor (the same that's in the diagram editor), so now you will at least be able to see whether an update request has completed/caused an error.
And like with the diagram, there's an alert if you try to navigate away from the screen while the status is in progress or error
> Entity Table Fixes

- ui/src/components/Toolbar/PagingButtons.jsx
- ui/src/util/normalizeDegreeValue.js
- ui/src/viewers/PdfViewer.jsx
- ui/src/viewers/PdfViewerPage.jsx
Fixes #1511 
Captures underlying rotate orientation value from loaded pdf page, then applies UI rotation to this value
See:
https://github.com/wojtekmaj/react-pdf/issues/277#issuecomment-424464542
> Reflect default PDF rotation

- aleph/model/collection.py
- aleph/pages/home.en.md
- site/aleph.occrp.org/pages/about.en.md
- site/aleph.occrp.org/pages/faq.en.md
- site/aleph.occrp.org/pages/home.en.md
- ui/src/app/Router.jsx
- ui/src/components/AuthButtons/AuthButtons.jsx
- ui/src/components/Collection/CollectionManageMenu.jsx
- ui/src/components/Collection/CollectionReindexAlert.jsx
- ui/src/components/Collection/CollectionReingestAlert.jsx
- ui/src/components/Dashboard/Dashboard.jsx
- ui/src/components/Entity/EntityInfoMode.jsx
- ui/src/components/Entity/EntityMappingMode.jsx
- ui/src/components/MappingEditor/MappingEditor.jsx
- ui/src/components/Navbar/Navbar.jsx
- ui/src/components/Navbar/Navbar.scss
- ui/src/dialogs/CollectionDeleteDialog/CollectionDeleteDialog.jsx
- ui/src/dialogs/CollectionEditDialog/CollectionEditDialog.jsx
- ui/src/dialogs/CollectionXrefDialog/CollectionXrefDialog.jsx
- ui/src/dialogs/CreateCaseDialog/CreateCaseDialog.jsx
- ui/src/dialogs/EntitySetCreateDialog/EntitySetCreateDialog.jsx
- ui/src/screens/CasesIndexScreen/CasesIndexScreen.jsx
- ui/src/screens/CollectionIndexScreen/CollectionIndexScreen.jsx
- ui/src/screens/CollectionScreen/CollectionScreen.jsx
- ui/src/screens/EntitySetIndexScreen/EntitySetIndexScreen.jsx
- ui/src/screens/GroupScreen/GroupScreen.jsx
- ui/src/screens/NotificationsScreen/NotificationsScreen.jsx
- ui/src/util/getCategoryLink.js
- ui/src/util/getCollectionLink.js
- replaced mentions of "personal dataset" with "investigation"
- new routes (with redirects) for /investigations and /investigation/:id
> Replace "Personal dataset" with "Investigation" in UI

- aleph/index/entities.py
- aleph/manage.py
- aleph/model/collection.py
This command is meant to serve any modeling needs by providing random
samples of data from aleph. The data can be filtered by whether it comes
from a secret collection or not and we can subsample and fix the random
seed. There is also filtering on entity schema in addition to which
properties must exist in the entity.
```
$ aleph sample-entities --help
Usage: aleph sample-entities [OPTIONS] [OUTFILE]
Sample random entities
Options:
--secret BOOLEAN     Whether to sample from secret collections (None means
sample from both)
-p, --property TEXT  Entities must have at least one of the listed
properties
-s, --schemata TEXT  Filter schematas
--seed INTEGER       Set the random seed
--sample-pct FLOAT   Random sampling percent (value from 0-1)
--limit INTEGER      Number of entities to return …
```
> Added `sample-entities` aleph command

- ui/src/components/EntitySearch/EntitySearchResults.scss
- ui/src/components/EntitySet/EntitySetIndex.jsx
- ui/src/components/EntityTable/EntityTable.jsx
- ui/src/components/common/QueryInfiniteLoad.jsx
- ui/src/components/common/ResultText.jsx
I modified the QueryInfiniteLoad component to only render the waypoint when loading more results is actually possible.  
This handles cases where:
- a user's viewport is larger than the first page of results, so the waypoint was never be triggered
- a user scrolls to the next waypoint while the previous page is still pending -> now the request for the next page will be sent when the previous page request is finished
> Infinite Scroll Debugging

- ui/src/components/Document/DocumentViewMode.jsx
- ui/src/viewers/PdfViewer.jsx
Fixes #1570 
I spent probably way too long trying to figure out a way to do this without the CDN, but it really seems that's the only way to ensure the pdf worker is loaded correctly - and is the officially recommended approach when using an un-ejected create-react-app. But PDFs are now loading so much more smoothly and it seems quickly as well.
This PR also fixes an issue where the entire app would flash into a brief loading state when the PDFViewer was lazy loaded for the first time.
> UI: PDF Viewer fixes

- ui/src/app/Router.jsx
- ui/src/components/AdvancedSearch/AdvancedSearch.jsx
- ui/src/components/Navbar/Navbar.jsx
- ui/src/components/Navbar/Navbar.scss
- ui/src/components/Screen/Screen.jsx
- ui/src/components/Screen/Screen.scss
- ui/src/components/common/DualPane.scss
- ui/src/screens/SearchScreen/SearchScreen.jsx
Avoid re-rendering navbar on every route change by factoring navbar component outside of router switch
I hope I didn't miss anything, but this ended up being a quite straightforward change.  And the whole in-app navigation loading feels a lot smoother / doesn't flash and re load the app logo every route change
> UI: Avoid re-rendering top nav

- ui/src/components/Facet/DateFacet.jsx
- ui/src/components/Facet/DateFacet.scss
- ui/src/components/Facet/util.js
Solves two issues currently with the date histogram filter (Both issues could, and maybe should? be solved on the request side of things instead, but this is a front-end solution just in case)
Issues:
1. Selecting a date range in the histogram currently sends a request which returns entities which might have additional date-type property values that lie outside the desired range, which is quite confusing and makes it feel like the histogram filter is not working.
Solution: in the Date Facet component, don't display intervals that fall outside the query range, if a range is specified.
2. The range of dates for entities I have access to in prod is currently the years 1000 - 9654, so the default histogram is pretty nonsensical.
Solution: in the Date Facet component, there are now default …
> UI: Date histogram filter bounds

- ui/package.json
- ui/src/app/Translator.jsx
- ui/src/app/blueprint-overrides.scss
- ui/src/app/layouts.scss
- ui/src/components/Entity/EntityActionBar.scss
- ui/src/components/Investigation/InvestigationOverview.jsx
- ui/src/components/Screen/Screen.scss
- ui/src/components/common/SectionLoading.jsx
- ui/src/components/common/SectionLoading.scss
- ui/src/index.js
It looks like the Intl polyfills are outside the scope of what can be finagled by messing with the targeted browserslist in create-react-app, so this branch includes a polyfill for both Intl.PluralRules and Intl.FormattedRelativeTime that is loaded dynamically depending on a user’s browser support (mainly relevant for Safari < 14).
(If we want to avoid some of this polyfill grossness we could instead do a fallback to replace the “a week ago” in notifications/exports with the simple date timestamp if a browser can’t support it…)
+ fixes for some other small Safari css weirdness
> UI: Safari Intl polyfill

- ui/src/components/Collection/CollectionXrefMode.jsx
- ui/src/components/Entity/EntityHeading.jsx
- ui/src/components/Entity/EntitySimilarMode.jsx
- ui/src/components/Profile/ProfileItemsMode.jsx
- ui/src/components/Profile/ProfileSimilarMode.jsx
- ui/src/components/XrefTable/XrefTable.jsx
- ui/src/components/XrefTable/XrefTableRow.jsx
- ui/src/components/common/EntityDecisionHotkeys.jsx
- ui/src/components/common/EntityDecisionRow.jsx
- ui/src/components/common/EntityDecisionRow.scss
- ui/src/components/common/index.jsx
Wrapped entity decision tables (as seen in collectionXrefMode, EntitySimilarMode, ProfileItemsMode, ProfileSimilarMode) in hotkeys wrapper
- Y: positive
- H: not enough information
- N: negative
- up: previous
- down: next
> Entity decision hotkeys

- Dockerfile
- aleph/index/entities.py
- aleph/manage.py
Doing the sampling inside ES led to hanging queries. So we do the sampling outside ES.
The other alternative is to do the sampling inside ftm-store database but we have to additionally implement property based filters in SQL in that case.
> Get rid of sample-entities command. Provide option to filter by secret and casefile flags when listing collections.

- aleph/logic/matching.py
`_make_queries` was creating fingerprints but just re-using the raw input
> Bugfix in logic/matching:_make_queries

- ui/src/app/App.scss
- ui/src/app/tables.scss
- ui/src/app/variables.scss
- ui/src/components/CollectionIndex/CollectionIndex.scss
- ui/src/components/Diagram/DiagramEditor.scss
- ui/src/components/EntitySearch/EntitySearchResults.scss
- ui/src/components/EntitySearch/EntitySearchResultsRow.jsx
- ui/src/components/Investigation/InvestigationHeading.scss
- ui/src/components/MappingIndex/MappingIndexItem.jsx
- ui/src/components/Notification/Notification.scss
- ui/src/components/Toolbar/DownloadButton.jsx
- ui/src/components/common/Entity.jsx
- ui/src/components/common/Entity.scss
- ui/src/components/common/EntityDecisionHotkeys.jsx
- ui/src/components/common/Mention.jsx
- ui/src/components/common/Mention.scss
- ui/src/dialogs/DocumentUploadDialog/DocumentUploadView.jsx
- ui/src/screens/SearchScreen/SearchScreen.jsx
Diagram Screen
Mentions
Table Document Viewer
Search Screen
Upload Dialog 
Investigation Sidebar
Notifications
> Downloadable table CSVs + other UI tweaks

- ui/src/components/QueryTags/QueryTags.jsx
- ui/src/screens/GroupScreen/GroupScreen.jsx
- Link from group screen to `/search` with group's collections pre-selected as filters
- Togglable display cutoff for query tags component to handle cases where many filters are active
> Group entities search

- aleph/util.py
> Link ES tasks to a trace id  and don't log ES request bodies to `_bulk` endpoint

- ui/src/app/initializeIconRenderer.jsx
- ui/src/components/Collection/CollectionManageMenu.jsx
- ui/src/components/Timeline/TimelineItemMenu.jsx
- Replaces deprecated blueprint Menu.Item and Menu.Divider with MenuItem and MenuDivider
- Replaces reference to deprecated blueprint Icon.SIZE_* 
- Implements a slightly different (better?) approach for overloading the default blueprint icon renderer to render custom ftm icons, by using a scale transform instead of messing with the svg viewport prop
> Replace deprecated blueprint Menu.* and Icon.* references

- ui/src/app/Query.js
- ui/src/components/Facet/DateFacet.jsx
- ui/src/components/Facet/Facet.jsx
- ui/src/components/QueryTags/QueryFilterTag.jsx
- ui/src/components/QueryTags/QueryTags.jsx
Fixes #1893 
@sunu @Rosencrantz - I realized we could use the existing supported elastic search operators on these date properties for the histogram API requests, so it was only some front-end component adaptation to show all of the date props as histograms :)
> Search Results: use date histogram for all date-type property filters

- aleph/authz.py
- aleph/settings.py
- aleph/tests/test_authz.py
- aleph/tests/test_collections_api.py
- aleph/tests/test_entities_api.py
- aleph/views/__init__.py
- aleph/views/archive_api.py
- aleph/views/base_api.py
- aleph/views/collections_api.py
- aleph/views/context.py
- aleph/views/entities_api.py
- aleph/views/entitysets_api.py
- aleph/views/mappings_api.py
- aleph/views/reconcile_api.py
- aleph/views/util.py
- ui/src/components/Screen/Screen.jsx
- ui/src/screens/ActivateScreen/ActivateScreen.jsx
- ui/src/screens/HomeScreen/HomeScreen.jsx
- ui/src/screens/HomeScreen/HomeScreen.scss
- ui/src/screens/PagesScreen/PagesScreen.jsx
Require auth for all non-index routes for apps with `metadata.auth.auth_required == true`.
TODO:
> Unauthenticated request handling

- aleph/search/query.py
- aleph/search/utils.py
When we sort by a field that may be undefined in certain schemas, by
default ElasticSearch will  leave out the entities where the field is
undefined from the sorted results.
We use the `unmapped_type` argument to force ElasticSearch not to leave
out those entities from the sorted search results.
Fixes #1857
> Make sure sorting by undefined field doesn't leave out entities

- ui/package.json
- ui/src/components/common/ErrorBoundary.jsx
- ui/src/components/common/index.jsx
- ui/src/screens/DiagramScreen/DiagramScreen.jsx
Introduces ErrorBoundary wrapper component (see https://reactjs.org/docs/error-boundaries.html) to catch errors rendered deeper in the component tree of a given component.
In the case of Network Diagrams this allows the page to still render even if the diagram renderer encounters an error, allowing for better error messaging to the user, easier debugging, and still allowing a user to access parts of the diagram like the export and metadata functionality even if there is a bug in the rendering flow.
Also includes a bugfix version bump for @alephdata/react-ftm
> Improved Error Handling for Network Diagrams

- aleph/settings.py
The CDN url in settings.py was set to a fixed version number, preventing us from pushing updates to the network diagrams code that is bundled with an embed.
@sunu @Rosencrantz I'm not so familiar with the python settings config, but if there is a way to fetch the version number from `ui/package.json` that would be preferable to using `latest`. But if not, then this works too.
> HOT FIX: Modified CDN url for diagram embeds to fetch latest version of package

- ui/src/components/Collection/CollectionView.jsx
- ui/src/components/Collection/CollectionViews.jsx
- ui/src/components/Collection/collectionViewIds.js
- ui/src/components/Document/DocumentManager.jsx
- ui/src/components/Investigation/InvestigationSidebar.jsx
- ui/src/components/Investigation/InvestigationViews.jsx
- ui/src/components/common/Schema.jsx
Fixes #2045 
Allows non-admin users to view the documents tab of a dataset 
@jlstro any thoughts on naming? I chose "Source documents" instead of something involving "File" because we're using "document" throughout the rest of the interface, but happy to change it to something else
> Show documents tab to non-admin users for datasets

- aleph/oauth.py
OIDC doesn't specify the format for access_token. Some providers use it
as a JWT to store information about groups (eg: Keycloak), some don't
use it as a JWT (eg: Google).
So we try to parse it as a JWT but if that fails we ignore the error
and move on. In case the access_token is not an JWT, the groups info is
stored in the id_token and that's where we look.
Fixes #2003
> Fix issue with Google OAuth integration

- Dockerfile
- aleph/index/xref.py
- aleph/logic/xref.py
- aleph/search/__init__.py
- aleph/settings.py
- aleph/views/xref_api.py
- requirements.txt
This PR puts the glm-bernoulli-2e model from `followthemoney-compare` into use for aleph's XREF system. In order to do so, the Dockerfile now downloads word frequency information and the model data from public.data.occrp.org and it's all loaded in `aleph.logic.xref`. The model is lazy-loaded on xref evaluation and we fall back to `followthemoney.compare` if the model can't be loaded.
Since the new model also has a measure of confidence associated to it, we added a `doubt` field to the xref index. The smaller this doubt is, the more confident we are in the result. This doubt parameter can be sorted on when requesting XREF from the API. (@kjacks afaik all we need to change the evaluation mode from random to this doubt is to change the requsted sort parameter to `&sort=doubt:desc`).
In order …
> Add followthemoney-compare model to XREF

- helm/examples/kind/Makefile
- helm/examples/kind/k8s/ingress.dev.yaml
- helm/examples/kind/k8s/ingress.staging.yaml
- helm/examples/kind/values/elasticsearch-data.yml
- helm/examples/kind/values/elasticsearch-master.yml
- helm/examples/kind/values/redis.yml
When setting up a local staging environment, i noticed that in the helm examples, elastic was using an old image and the ingresses were using a deprecated api.
besides that i removed configuration that matched the defaults, and removed the `PREFIX` from the makefile as "aleph" was also used in the default secrets.
> Update helm examples

- ui/src/util/convertUTCDateToLocalDate.js
While being 9 hours time zone shifted, I noticed an issue with how we're converting UTC time stamps from the db into local time when the difference crosses a date line - the UI was showing times in the future, which would never be possible.
We were previously using the solution proposed here: https://stackoverflow.com/a/18330682
But as comments suggest, there are some issues with this approach, so now using the top-rated solution. (tested in Chrome, Firefox, and Safari)
> Notifications relative local time bug

- aleph/logic/xref.py
- aleph/tests/test_xref.py
Match.collection_id should be set to the collection_id of the xref match
> Hotfix: Use the correct collection_id while generating xref matches

- ui/src/screens/HomeScreen/HomeScreen.jsx
This PR fixes the submit handler for the search input on the home screen.
To reproduce, open the [OCCRP Aleph instance](https://data.occrp.org), make sure you’re logged-out, enter any string into the search input, and press enter. The app should navigate to the `/search` route, but instead nothing happens.
Navigation fails, because the navigate prop on the `HomeScreen` component is undefined. The `HomeScreen` component needs to be wrapped in the `withRouter` HOC in order to have access to the `navigate` prop.
> Fix search handler on home screen

- docker-compose.yml
Gunicorn's workers crash when uploading large files to Aleph Api due to short default timeout. Added a timeout flag to docker compose file. This fixes the issue.
> Fixed Gunicorn worker timeout issue

- aleph.env.tmpl
Sample searches are now configured in `aleph/pages/home.en.md` and `ALEPH_SAMPLE_SEARCHES` is not used anymore
> Remove ALEPH_SAMPLE_SEARCHES from aleph.env.tmpl

- aleph/tests/test_view_util.py
- aleph/views/util.py
When there are multiple validation errors for the same path, the response error messages get overrided
This PR fixes that by concatenating error messages for the same path
> Concatenate error messages for the same path

- Makefile
Currently, running `make worker` fails as the aleph CLI is installed at `/usr/bin/aleph` (not `/usr/local/bin/aleph`). This has previously been reported in #2093.
I’m not really sure though what has changed since the commit that introduced the absolute path to `/usr/local/bin/aleph` (https://github.com/alephdata/aleph/commit/f2824360c7032e98bb9944710feb978641a93181). I quickly looked through the history of files that might be relevant (setup.py, Dockerfile + compose config, …), but didn’t find anything.
> Fix worker target in Makefile

- ui/src/components/Dashboard/Dashboard.jsx
- ui/src/components/Navbar/Navbar.jsx
- ui/src/components/common/LinkButton.jsx
- ui/src/components/common/LinkMenuItem.jsx
- ui/src/components/common/index.jsx
- ui/src/screens/PagesScreen/PagesScreen.jsx
Unfortunately, Blueprint makes it quiet hard to render valid, accessible HTML markup with its `AnchorButton` and `MenuItem` components. Currently, we’ve been using different workarounds (e.g. using `onclick` handlers rather than links or nesting buttons withink anchor tags), which e.g. makes it impossible to copy the URL or open a link in a new tab, and breaks assistive technology.
Fortunately, with recent versions of React Router, it’s become easier to do this in a way that doesn’t produce inaccessible markup: The `useLinkClickHandler` and `useHref` tags provide the behavior needed to support client-side navigation with existing components like `AnchorButton` and `MenuItem`.
The `LinkMenuItem`/`LinkButton` components behave like React Router’s `Link` component and render like their …
> Add LinkMenuItem, LinkButton to replace inaccessible workarounds

- ui/package.json
There are a few packages in our `package.json` that we don’t use/import. The UI still builds successfully after uninstalling them. I also checked the git history to ensure I’m not missing anything. For most of them, it seems the code that relied on the packages has simply been removed from the Aleph codebase:
* `numeral`: The components that relied on this have been extracted into `react-ftm`, so we don’t need it as a direct dependency anymore.
* `jwt-decode`: Hasn’t been needed anymore since [this change](https://github.com/alephdata/aleph/commit/778d0809c7598206b847a405095fbe57266a7440).
* `react-json-pretty`: This package was used in a feature preview that has since been removed/changed and the package isn’t used anymore.
* `file-selector`: No idea how this package was used in the …
> Remove unused packages

- ui/src/components/XrefTable/XrefTable.jsx
- ui/src/components/common/QueryInfiniteLoad.jsx
As I haven’t been able to reproduce an API response that leads to this bug locally, I’ve been using mitmproxy to intercept the API requests and modify the response.
I’ve been wondering though if we should actually merge this. In most cases where we get an inconsistent API response (i.e. a response that should contain results, but doesn’t), we would want to look into the underlying issue/bug. This change would basically hide the bug from the UI, which will make it more difficult to notice in the first place. @Rosencrantz what do you think?
***
If you want to test this locally, follow these steps:
1. Start Aleph.
2. Install mitmproxy if you haven’t yet: `brew install mitmproxy`.
3. Run `mitmweb -p 8888` to start the proxy and open the web UI.
4. Set up your web browser to use …
> Fix infinite scroll in case no results are returned

- ui/src/components/EntityTable/EntityTable.jsx
Previously, we only linked to referenced entities in case the *referencing* entity is a thing.
As discussed in #2338, we actually considered this a bug. The original intent of this condition was probably to check if the *referenced* entity is a thing. Non-thingy entity views do not offer a lot of additional information and are mostly blank, so it doesn’t make a lot of sense to link to them.
That doesn’t seem something that’s possible right now with FtM – referenced entities are always things (see https://github.com/alephdata/aleph/issues/2338#issuecomment-1170420470), so I devided to simply render links to referenced entities in all cases.
Closes #2338
> Navigate to entites referenced in entity tables

- aleph/core.py
- aleph/model/role.py
Because:
```python
>>> def foo(x, y=[]):
...   y.append(x)
...   print(y)
... 
>>> foo(1)
[1]
>>> foo(2)
[1, 2]
```
None of the code here mutates, but this removes the possibility of introducing errors down the line.
> removed code smell of function args with mutable defaults

- ui/package.json
This bumps `react-ftm` to include a fix that prevented the timeline editor being rendered in Aleph. See https://github.com/alephdata/react-ftm/pull/895.
Steps to verify the fix:
1. Rebuild the UI container to ensure the latest packages are installed:
```
docker compose -f docker-compose.dev.yml build ui
```
2. Upgrade indices and start Aleph:
```
make upgrade
make web
```
3. Open the UI: http://localhost:8080
4. Create a new timeline.
5. Navigate to the timeline and click the button "Create new item".
6. You should see the timeline editor. You should be able to hover over the color picker’s swatches and see tooltips with the color names.
> Fix timelines editor

- ui/src/components/EntitySearch/FacetedEntitySearch.jsx
- ui/src/components/EntitySearch/FacetedEntitySearch.scss
It's a really small change which makes the toggle filters sidebar button persistent within Aleph. Currently unless you are hovering over the very find line you would not know that this thing exists.
> Make the hide filter button persistent

- aleph/search/parser.py
- aleph/search/query.py
ES errors out when the length of a result body is larger than the global limit for highlight analysis (defined by
`index.highlight.max_analyzed`_offset). We set [`max_analyzed_offset`](https://www.elastic.co/guide/en/elasticsearch/reference/current/highlighting.html#:~:text=to%20true.-,max_analyzed_offset,-By%20default%2C%20the) to be lower than the global setting in highlight queries to prevent those errors.
The other option was to increase the global limit. But that puts more pressure on the index.
> Quickfix: Set the `max_analyzed_offset` setting to prevent ES errors

- .github/workflows/build.yml
- aleph/search/parser.py
- aleph/search/query.py
- aleph/tests/test_search_query.py
- ui/package.json
- ui/src/components/EntitySearch/EntitySearchResults.scss
- ui/src/components/EntitySearch/EntitySearchResultsRow.jsx
- ui/src/components/common/SearchHighlight.jsx
- ui/src/components/common/SearchHighlight.scss
- ui/src/components/common/SearchHighlight.test.jsx
- ui/src/components/common/index.jsx
- ui/src/setupTests.js
- ui/src/util/convertHighlightsToReactElements.js
- ui/src/util/convertHighlightsToReactElements.test.jsx
- ui/src/util/htmlEntities.js
- ui/src/util/insertHighlights.js
- ui/src/util/insertHighlights.test.js
- ui/src/viewers/PdfViewer.jsx
- ui/src/viewers/PdfViewer.scss
- ui/src/viewers/PdfViewerPage.jsx
- ui/src/viewers/PdfViewerSearch.jsx
- ui/src/viewers/TextViewer.jsx
- ui/src/viewers/TextViewer.scss
- ui/src/viewers/TextViewer.test.jsx
This PR adds support to highlight search terms in document text while in plaintext mode. It would be nice to support this in view mode as well, but this is likely going to be less straight-forward and something I’d look into separately.
https://user-images.githubusercontent.com/1512805/178830658-b1071061-1523-4d77-8de3-04d7b0f7b575.mov
Example document that can be used for testing: [test_markup.pdf](https://github.com/alephdata/aleph/files/9071458/test_markup.pdf)
> Display highlights in document plaintext view mode

- ui/src/screens/ActivateScreen/ActivateScreen.jsx
This bug was probably introduced when upgrading to React Router v6. `ActivationScreen` needs to be wrapped in the `withRouter` HOC in order to access URL parameters.
Closes #2505
> Fix activation screen

- ui/src/util/convertUTCDateToLocalDate.js
Closes #2488. Related to #2489.
The Aleph API returns dates in UTC as ISO strings without timezone designators. Parsing a date in JS (`new Date(dateString)`) uses the local timezone, and there’s no way to explicitly specify a timezone to use.
We currently have a helper function that replaces the local timezone with UTC. It does this by simply appending "UTC" to the string representation of a date in order to override the time zone.
This does however results in a date string that has multiple time zones:
```js
const date = new Date()
console.log(`${date} UTC`);
// "Wed Aug 31 2022 20:01:20 GMT+0200 (Central European Summer Time) UTC"
```
Firefox and Chrome parse these date strings, even though they are invalid. Safari throws an error.
This PR replaces the helper implementation with a way …
> Fix date helper

- ui/src/actions/index.js
- ui/src/actions/messagesActions.js
- ui/src/app/Router.jsx
- ui/src/app/store.js
- ui/src/components/MessageBanner/MessageBanner.jsx
- ui/src/components/MessageBanner/MessageBanner.scss
- ui/src/components/MessageBanner/MessageBanner.test.jsx
- ui/src/reducers/messages.js
- ui/src/selectors.js
Currently, there’s no way to close/dismiss the message banner. This can be annoying, especially when displaying less important information for a long time, as it takes up vertical screen estate.
This adds the ability to optionally let users dismiss a message.
https://user-images.githubusercontent.com/1512805/196056539-0bc914be-a889-48e4-988c-53653044e6e1.mov
In order to implement this, the IDs of the five most recently dismissed messages are persisted in local storage. Storing all messages a user has ever dismissed is probably unnecessary and could potentially bloat the local storage.
> Dismissible message banner

- ui/src/viewers/TableViewer.jsx
**This PR is based on https://github.com/alephdata/aleph/pull/2478 as it includes changes to components in react-ftm. Merge https://github.com/alephdata/aleph/pull/2478 first, then change the PR target to develop.**
***
When ingesting CSV files (and probably also other tabular file formats), the resulting CSV file that’s stored in the archive contains a new line file ending.
When we request and parse the CSV file in the frontend, the CSV parser we use emits only a single empty cell for the last row. When we were trying to render other cells in that row, the cell value would always be "undefined" and a skeleton loader would be displayed indefinitely.
Instead, we now compare the number of rows that have been already loaded with the row index of the cell to be rendered.
Closes #2377
> Handle table rows with incorrect number of columns

- ui/src/components/common/ItemOverview.scss
**This PR is based on https://github.com/alephdata/aleph/pull/2478 as it includes changes to components in react-ftm. Merge https://github.com/alephdata/aleph/pull/2478 first, then change the PR target to develop.**
***
`overflow-wrap: break-word` does break words if text is otherwise unbreakable, but those soft-break opportunities are not considered when calculating the intrinsic size of elements. If the title contains block/inline-block elements (e.g. the Transliterate component) this can result in overflows.
Using `overflow-wrap: anywhere` instead solves the issue. Fixes #2554.
> Prevent unbreakable title from causing overflow

- ui/src/components/common/SchemaCounts.jsx
**This PR is based on #2478 as it includes changes to components in react-ftm. Merge #2478 first, then change the PR target to develop.**
***
Fixes #2415. Previously, the scroll position of the dropdown would reset on every rerender (even if the options had not changed).
Rerenders happen in regular intervals, because we update the collection in regular intervals (every 30 seconds and even every 3 seconds if the collection is currently being indexed). As a consequence, the it is basically impossible to select an option somewhere down the list while the collection is being indexed.
You can observe the behavior in the video below. At the same time the API request appears in the developer tools, the scroll position resets.
https://user-images.githubusercontent.com/1512805/186433833-16227511-97 …
> Do not reset schema select scroll position on rerender

- .github/workflows/build-ui.yml
- .github/workflows/build.yml
- .gitignore
Right now, we always run the backend/UI job even if only files related to the UI/backend have changed.
This is annoying and can block work, because GitHub Actions limits the number of concurrent jobs. In some cases (e.g. after Dependabot has opened a lot of PRs) this can lead to jobs being queued for quite some time.
Limiting the number of jobs that are triggered based on the files changed can help speed up CI runs.
Closes #2485
***
This is how I tested the changes.
1. Committed and pushed a new file in `/ui`. This commit triggered only the `build-ui.yml` workflow.
2. Committed and pushed a new file in `/aleph`. This commit triggered only the `build.yml` workflow.
4. Committed and pushed a new file in the root directory. This commit triggered both workflows.
> Run UI and Backend jobs only when necessary

- ui/package-lock.json
- ui/package.json
- ui/src/bezier-js.d.ts
- ui/src/react-ftm/components/NetworkDiagram/renderer/EdgeRenderer.tsx
The way we import `bezier-js` was incompatible with out build setup, resulting in `Bezier` being `undefined`. Due to this, adding a curved/bezier line in a network diagram would raise an error.
This fixes the import and also updates `bezier-js` to the latest version.
You can verify that this solves the issue by creating a curved line in a network diagram:
https://user-images.githubusercontent.com/1512805/196520937-1497275a-d814-43cf-8107-f3a576174969.mov
> Fix error when rendering bezier curve in network diagrams

- ui/src/components/AuthButtons/AuthButtons.jsx
We didn’t used well structured markup for the auth button popover that resulted in the color and alignment being slightly off.
| Before | After |
| - | - |
| <img width="210" alt="Screen Shot 2022-10-19 at 11 39 17" src="https://user-images.githubusercontent.com/1512805/196658147-e240b83c-b2cf-46f6-befc-222bcf815848.png"> | <img width="218" alt="Screen Shot 2022-10-19 at 11 46 30" src="https://user-images.githubusercontent.com/1512805/196658175-016b4e50-b4f7-493b-8fc9-7e29cf8e4415.png"> |
> Fix icon color and alignment in auth popover

- docker-compose.dev.yml
The latest version of ingest-file (4.x) already contains changes to use RabbitMQ as the tasks queue which is incompatible with the current version of Aleph.
> Pin ingest-file version in development environment

- ui/src/react-ftm/editors/PropertyEditor.tsx
This is the result of automatically replacing all occurrences of `.bp4-` with `.#{$bp-ns}`. This obviously only works in SCSS though.
> Fix invalid selector

- aleph/settings.py
- aleph/validation/spec.py
- aleph/views/__init__.py
- aleph/views/base_api.py
- aleph/views/bookmarks_api.py
- ui/src/actions/bookmarkActions.js
- ui/src/actions/index.js
- ui/src/app/store.js
- ui/src/components/Entity/EntityToolbar.jsx
- ui/src/components/Navbar/Navbar.jsx
- ui/src/components/common/BookmarkButton.tsx
- ui/src/components/common/BookmarksDrawer.scss
- ui/src/components/common/BookmarksDrawer.tsx
- ui/src/components/common/BookmarksList.scss
- ui/src/components/common/BookmarksList.tsx
- ui/src/components/common/index.jsx
- ui/src/reducers/bookmarks.js
- ui/src/reducers/index.js
- ui/src/screens/EntityScreen/EntityScreen.jsx
- ui/src/selectors.js
A very simple, client-side only implementation of a bookmarks feature for Aleph. Allows users to bookmark entities and quickly view a list of all bookmarks anywhere in the app.
**To consider:**
* Bookmarks may not be a perfect/flexible-enough solution for some cases. For example, some users want to mark/tag entities as sighted so they know they don’t have to look at the entities again when it appears e.g. in the results for another search.
* Some users would like to add a list of relevant entities from *other* datasets to an investigation.
* Some users would like to add tags/bookmark entities/mark entities as sighted in a way that can be shared across everyone who works on an investigation.
**To do:**
**Possible future improvements:**
> Bookmarks MVP

- ui/src/components/MessageBanner/MessageBanner.jsx
- ui/src/components/MessageBanner/MessageBanner.scss
In some cases, this may cause the button to shrink and the button text overlaying the message text.
**Before:**
This adds some whitespace between the button and the message text and also ensures that the button is wide enough for the label text.
**After:**
> Fix visual quirk when displaying long, dismissible messages

- ui/package.json
- ui/src/components/MessageBanner/MessageBanner.jsx
I forgot about this so often it's embarrassing. Enabling the linter rule will ensure our CI fails when we use props for HTML elements that are named differently in JSX/React.
> Use className instead of class, enable linter rule 🤦‍♂️

- ui/src/components/common/BookmarksDrawer.tsx
The download button is only displayed if a user has bookmarked at least one entity. In case a user has no bookmarks, the colon "leads to nowhere".
> Fix interpunctuation

- ui/src/react-ftm/components/NetworkDiagram/GraphConfig.ts
- ui/src/react-ftm/components/NetworkDiagram/renderer/VertexRenderer.tsx
- ui/src/react-ftm/components/NetworkDiagram/toolbox/EntityViewer.tsx
- ui/src/react-ftm/editors/ColorPicker.tsx
- ui/src/react-ftm/utils/index.ts
- ui/src/react-ftm/utils/mapColor.ts
- ui/src/react-ftm/utils/reduceTranslucentColor.test.ts
- ui/src/react-ftm/utils/reduceTranslucentColor.ts
This updates the default colors that can be selected using the color pickers to a lighter shade. With the Blueprint 4 update, the darkest shade that we’re currently using looks a bit too dull and grayish for use in a visualization.
Depending on when the the vertices in a network diagram were created, colors will be slightly different. So this also ensures that all colors are consistent across different network diagrams and – more importantly – within network diagrams.
In the screenshots below, the vertices in the left column have been created before we rolled out the BP4 upgrade, the vertices in the middle column have been created using the current 3.13.0 RC, and the vertices in the right column have been created after changing the default colors to a lighter shade.
Closes #2657
| Before …
> Migrate different legacy colors to the new Blueprint 4 color palette

- ui/src/components/common/Entity.jsx
I observed this issue in a recent user research session. The user wanted to view search results in a separate window or tab.
Right now, we always prevent the default browser behavior and open the preview drawer, even if the user has pressed a modifier key while clicking a link. This prevents users from opening entity links in a new tab or window.
This PR only prevent the native browser behavior if no modifier keys (Cmd, Ctrl, Alt, Shift) are pressed while clicking on the link. That means that users can now:
* Cmd+Click to open a search result in a new tab, in the background.
* Cmd+Shift+Click to open a search result in a new tab, in the foreground.
Fix #2713
> Fix native click behavior search results

- docker-compose.dev.yml
This allows us to use tools like dejavue [1] to inspect index contents which is slightly more convenient than sending requests directly to the ES API.
I’ll eventually add this to the technical documentation or the Readme. For now, here’s what’s worked well for me:
1. Run `docker run -p 1358:1358 -d appbaseio/dejavu` to start dejavue
2. Open the web interface at http://localgost:1358
3. Enter the ES endpoint (`http://localhost:19200`) and the name of the ES index. Entity indices follow the follow the pattern `aleph-entity-schema-v1`. For example the index for the `LegalEntity` schema would be `aleph-entity-legalentity-v1`.
4. Click "Connect".
[1] https://github.com/appbaseio/dejavu
> Enable CORS for Elasticsearch API in development environment

- ui/Dockerfile
Fixes #2695
We’re currently using Node.js 16 which will reach EOL in Sep 2023. The current LTS version is 18 (see [release schedule](https://github.com/nodejs/release#release-schedule)).
This upgrades only the base image used in development and when building the UI (`Dockerfile`). 
The base image used to serve the static UI assets in production is `nginx:alpine` (as specified in `Dockerfile.production`) and stays untouched.
> Upgrade to the latest LTS Node.js version

- .github/workflows/docs.yml
Right now, the docs workflow is triggered every time a commit is pushed. This is unnecessary, can delay execution of other workflows, and can cause notification spam.
The `/docs` directory is completely self-contained (at least at the moment), i.e. it is fine to only run the docs workflow if the diff affects files in this directory.
> Run docs workflow only if docs directory as changes

- docs/src/pages/developers/developer-tools.mdx
After the migration away from pdflib we are going to deprecate it, so there is no need to mention it.
> Remove pdflib mention from docs

- ui/src/components/common/BookmarkButton.tsx
- ui/src/components/common/BookmarksDrawer.tsx
- ui/src/reducers/config.js
This PR…
1. improves the wording of the existing warning message to clarify that clearing browsing data or switching devices can cause bookmarks to get deleted,
2. adds a separate warning message popover when bookmarking something for the first time.
https://user-images.githubusercontent.com/1512805/215151100-a3802ed6-aec9-4792-937b-e9818b5043d5.mov
> Improve bookmarks warning messages

- ui/src/app/blueprint-overrides.scss
- ui/src/dialogs/AuthenticationDialog/AuthenticationDialog.jsx
- ui/src/dialogs/AuthenticationDialog/AuthenticationDialog.scss
Closes #2806. This allows users to switch between signin/signup any time and always resets the dialog state when closing and reopening it.
In addition to fixing the referenced bug, I’ve also sneaked in a few minor styling fixes.
https://user-images.githubusercontent.com/1512805/212868415-9c4b5080-5d09-45ce-add7-e5843ec0fb32.mov
> Reset signin modal state after closing or when switching between signin and signup

- .github/workflows/main.yml
The diff is weird because the file used to have DOS-style line endings, which I made consistent with all other files in the repo. The only change is in the last line, allowing us to skip this action if it fails (and not take down the whole build with it). See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error
> Allow add-to-project to fail

- ui/src/components/Timeline/Timeline.test.tsx
- ui/src/components/Timeline/TimelineItemCreateDialog.tsx
- ui/src/components/Timeline/TimelineItemCreateForm.test.tsx
- ui/src/components/Timeline/TimelineItemCreateForm.tsx
- ui/src/components/Timeline/util.ts
The end date of a timeline item is always optional. This adds "(optional)" after the respective form labels to make this clear for users. Additionally, this also adds proper validation to required fields (i.e. you can’t create a timeline item without a start date).
> Indicate optional fields when creating new timeline items

- aleph/logic/roles.py
- aleph/manage.py
Usage: 
`aleph renameuser user@example.com Bob`
To rename the default `Aleph` user, the command is:
`aleph renameuser default CorpName`
> Add renameuser CLI command

- ui/src/components/Timeline/Timeline.test.tsx
- ui/src/components/Timeline/Timeline.tsx
- ui/src/components/Timeline/state.ts
- ui/src/components/Timeline/util.ts
The current implementation was using `useEffect` to trigger an API request (via the `onLayoutUpdate` callback) whenever the layout state (for example the color of an entity set item) changes. As `useEffect` will also execute the side effect on initial render, this caused an undesired API request directly after opening a timeline.
Instead of relying on `useEffect` to persist the layout state, this now triggers the `onLayoutUpdate` callback explicitly when the user performs certain actions (like changing the color of an item).
> Do not save timeline layout on initial load

- ui/src/components/EntitySet/EntitySetManageMenu.jsx
Previously, we would display the settings and delete action buttons for read-only timelines and lists. This PR hides them and only displays them if the current user does actually have write access to a timelines or list.
| | Before | After |
| --- | --- | --- |
| Timelines | <img width="1003" alt="Screen Shot 2023-03-09 at 10 20 25" src="https://user-images.githubusercontent.com/1512805/223977569-7077a423-9187-4b42-a71f-c003903b4dc4.png"> | <img width="1006" alt="Screen Shot 2023-03-09 at 10 20 43" src="https://user-images.githubusercontent.com/1512805/223977613-f929c367-3fdd-47b0-8f03-e8bdc1174ddd.png"> |
| Lists | <img width="1005" alt="Screen Shot 2023-03-09 at 10 21 21" src="https://user-images.githubusercontent.com/1512805/223977401-40ad7d84-72e0-4125-8057-ff04678a27f2.png"> | <img …
> Do not render delete and settings actions for read-only timelines, lists

- ui/src/components/Timeline/Timeline.scss
- ui/src/components/Timeline/Timeline.tsx
- ui/src/components/Timeline/TimelineChart/TimelineChart.scss
- ui/src/components/Timeline/TimelineChart/TimelineChart.test.tsx
- ui/src/components/Timeline/TimelineChart/TimelineChart.tsx
- ui/src/components/Timeline/TimelineChart/TimelineChartGrid.scss
- ui/src/components/Timeline/TimelineChart/TimelineChartGrid.tsx
- ui/src/components/Timeline/TimelineChart/TimelineChartItem.scss
- ui/src/components/Timeline/TimelineChart/TimelineChartItem.tsx
- ui/src/components/Timeline/TimelineChart/TimelineChartLabels.scss
- ui/src/components/Timeline/TimelineChart/TimelineChartLabels.tsx
- ui/src/components/Timeline/TimelineChart/TimelineChartPopover.tsx
- ui/src/components/Timeline/TimelineChart/util.test.ts
- ui/src/components/Timeline/TimelineChart/util.ts
- ui/src/components/Timeline/TimelineItemCreateDialog.tsx
- ui/src/components/Timeline/TimelineList/TimelineList.test.tsx
- ui/src/components/Timeline/state.test.ts
- ui/src/components/Timeline/state.ts
- ui/src/components/Timeline/types.ts
- ui/src/components/Timeline/util.ts
This adds three different zoom levels (days/months/years) for the new timelines chart view. The default zoom level is "months".
The chart view is currently not enabled in the UI. In order to enable it, add a `renderer="chart"` property to the `Timeline` component here:
https://github.com/alephdata/aleph/blob/267d93611846c079cc72838ef5464d0878506c62/ui/src/screens/TimelineScreen/TimelineScreen.jsx#L195-L204
***
**Possible future enhancements:**
> Allow users to switch between timeline day/month/year zoom levels

- ui/src/components/Timeline/util.ts
Babel (used by create-react-app) seems to compile away the named capturing groups in production builds. As a result, `result.groups` is always undefined. We could make this work by configuring Babel correctly. However, that would require even more dirty overrides of the default create-react-app configuration. So this simply updates the code to not rely on named capturing groups anymore. Slightly less readable, but works just fine!
> Remove named capturing groups

- ui/src/components/Timeline/Timeline.test.tsx
- ui/src/components/Timeline/TimelineItemCreateForm.test.tsx
- ui/src/components/Timeline/TimelineItemCreateForm.tsx
- ui/src/components/Timeline/util.test.ts
- ui/src/components/Timeline/util.ts
* Allows users to add items with imprecise/vague dates (e.g. `2022` or `2022-01`).
* Allows users to enter (or copy-paste) dates without hyphens (e.g. `20220322` or `202203`).
> Fix unsupported date formats

- ui/src/components/Timeline/Timeline.scss
- ui/src/components/Timeline/Timeline.tsx
- ui/src/components/Timeline/TimelineCallout.scss
- ui/src/components/Timeline/TimelineCallout.tsx
- ui/src/components/Timeline/TimelineChart/TimelineChart.test.tsx
- ui/src/components/Timeline/TimelineChart/TimelineChart.tsx
- ui/src/components/Timeline/TimelineList/TimelineList.scss
- ui/src/components/Timeline/TimelineList/TimelineList.test.tsx
- ui/src/components/Timeline/TimelineList/TimelineList.tsx
- ui/src/components/Timeline/TimelineList/TimelineListItem.scss
- ui/src/components/Timeline/TimelineList/TimelineListItem.test.tsx
- ui/src/components/Timeline/TimelineList/TimelineListItem.tsx
- ui/src/components/Timeline/state.ts
**Note:** This PR is set up to be merged into the 3.14 release branch, but I think it would also be fine to merge it into develop and include it in the next release.
*** 
This displays timeline items (in list view) even if an item doesn’t have a valid date. Items without valid dates are displayed at the top of the list.
When creating new items through the timelines UI, dates are validated and users shouldn’t be able to add a new items without a valid date. However, that’s not the only way to add items to a timeline. Users may have created entities in network that don’t have dates yet (because dates aren’t a top priority when mapping out organization structures and relationships in a diagram). So when they add these existing entities to a timeline, we need to make users aware of the fact …
> Show timeline items with invalid dates

- ui/src/components/EntityTable/EntityTable.jsx
This allows users to add existing entities of most schemata to timelines. Until now, this was only supported for interval entities (due to the limitations of the old timelines).
Note: Right now, when adding an existing entity that has now filled out date property (e.g. a company without an incorporation date), this entity wouldn’t be visible when displaying the timeline. This will be resolved as soon as #2963 is merged.
https://user-images.githubusercontent.com/1512805/233866664-f6d516b7-509b-4dcf-9bba-0610944141ad.mov
Ref #2673
> Add existing entities to timelines

- .github/workflows/build-ui.yml
- .github/workflows/build.yml
We have implemented a process that uses release candidates for pre-release testing and deployments, so there’s no need anymore to push Docker images for every commit. This is wasteful in terms of bandwidth and storage resources and clutters the image repository.
@catileptic @Rosencrantz @stchris This is something we have discussed a few times before, tbh I’m not sure anymore what exactly our conclusion was. Let me know if you have concerns or in case we do actually still depend on images built from commits that are not tagged.
> Push Docker images for tags only

- e2e/models/investigations.py
- ui/src/components/common/DeleteDialog.tsx
- ui/src/components/common/index.jsx
- ui/src/dialogs/CollectionDeleteDialog/CollectionDeleteDialog.jsx
- ui/src/dialogs/EntitySetDeleteDialog/EntitySetDeleteDialog.jsx
Recently, we had to handle multiple support cases of users deleting collections and entity sets by accident. In some cases, this was because users thought they were only deleting an entity within the investigation or entity set. Even though we do show a confirmation dialog before destructive actions, users often do not read the actual dialog message.
In order to prevent users from deleting data by accident, this PR adds an additional confirmation UI before deleting collections or entity sets and asks users to confirm the title of the collection/investigation.
The following video shows the flow to delete a collection:
https://user-images.githubusercontent.com/1512805/234068743-d6768c09-d2d4-47ad-8a0f-41ab9175cb99.mov
The flows for deleting entity sets (diagrams, lists, timelines, profiles) …
> Add additional confirmation UI before destructive actions

- ui/src/components/Timeline/TimelineItemCreateForm.test.tsx
- ui/src/components/Timeline/TimelineItemCreateForm.tsx
- ui/src/components/Timeline/util.test.ts
- ui/src/components/Timeline/util.ts
FtM supports times in date properties (see [docs](https://followthemoney.tech/explorer/types/date/)), but when adding items to a timeline in Aleph, you can’t add a time.
Additionally, if a timeline contains an item with a datetime value, an unhandled error occurs when switching to the chart view.
This PR fixes both issues. When adding a new timeline item, the form now allows entering values like `2023-05-02T00:00:00` or `2023-05-02 00:00`.
When parsing those dates, we now simply ignore the time part. This also ensures that the chart view renders successfully.
Closes #3009
**To do:**
> Allow users to add timeline items with times

- ui/src/app/variables.scss
- ui/src/reducers/util.js
When searching, we keep the search results in the Redux store in a structure similar to the following:
```json
{
"entities": {
"abc123": {
"id": "abc123",
"schema": "Company",
"highlight": "<em>Twitter</em> is an online social media and social networking service."
}
},
"results": {
"entities?filter:schemata:Company&highlight=true&limit=30&q=twitter": {
"total": 1,
"page": 1,
"results": ["abc123"]
}
}
}
```
After clicking on one of the search results, we load detailed entity data and use the detailed data to replace the (partial) entity data from the initial search request. However, the response from the second request does not contain the search highlight, i.e. the highlight is removed from the state when loading additional entity data.
We can work around this by merging data instead of …
> Fix search highlights disappearing when opening entity previews

- ui/src/components/Timeline/TimelineChart/TimelineChartItem.scss
This is a super tiny fix for a tiny visual problem (other’s have noticed it too though, it’s not just me!)
Right now, the labels of timeline items stick to the left viewport edge with no whitespace.
https://github.com/alephdata/aleph/assets/1512805/1f4652e0-eddd-42b1-b1c1-d5591a3528c0
This PR fixes that:
https://github.com/alephdata/aleph/assets/1512805/412febcd-5c73-4858-92e3-3e7d7ce74167
> Fix whitespace in timelines chart view

- ui/src/dialogs/CollectionEditDialog/CollectionEditDialog.jsx
See #3060 for details. Decided to go with the second option and adjusting the UI form to send actual `null` values (instead of empty strings) in case fields are empty rather than relaxing the validation. After thinking about it for 5 more minutes, this felt like the cleaner solution.
> Send null value if collection metadata fields are empty

- helm/charts/aleph/values.yaml
The currently referenced `3.18.1` version does not exist.
> bump ingestfile to 3.18.4

- ui/Dockerfile
While working on https://github.com/alephdata/aleph/pull/2755 a CI run triggered a build of the UI container which failed because of no installation candidate for `python` (see https://github.com/alephdata/aleph/actions/runs/5276096256/jobs/9542371623?pr=2755). 
We are based off of `node:18-slim` which got[ updated 2 days ago](https://hub.docker.com/layers/library/node/18-slim/images/sha256-ce802ad553e7957cd2c01fcecab98b39689f6e54cbb173c2538aac18db310795?context=explore), seemingly to be based off of the newly released Debian 12 (Bookworm).
This change here makes the build work, but I'm not entirely sure where exactly `python` is invoked in the build chain so we may need to do other changes as well.
> UI docker image python package

- .github/workflows/build.yml
- CONTRIBUTING.md
- Makefile
- aleph/logic/expand.py
- aleph/logic/html.py
- aleph/logic/matching.py
- aleph/logic/profiles.py
- aleph/search/parser.py
- aleph/search/query.py
- aleph/tests/util.py
- contrib/play/tripler.py
- e2e/models/__init__.py
- requirements-dev.txt
- ruff.toml
https://github.com/charliermarsh/ruff replaces flake8 + black (and can also auto-fix lots of things).
```
$ time make lint
ruff check .
make lint  0.01s user 0.03s system 47% cpu 0.091 total
```
> Use Ruff for linting

- aleph/search/__init__.py
- aleph/tests/test_collections_api.py
The collections search returns results with exact matches only. Users do however expect the search to be fuzzy by default, i.e. "Romania" should also match "Romanian" etc. By changing the query type from `query_string` to `multi_match`, we can use fuzzy search by default.
The advantage of using fuzzy search is that it is applied at search time, i.e. we do not need to change the index configuration or re-index contents.
The main disadvantage is that it doesn't cover all variations that would be covered if we used proper stemming. For example, the following variations are not matched:
* Contracts/contracting
* Company/companies
* Malta/Maltese
Also, fuzzy search cannot be combined with prefix search (for example "Open" does not match "OpenContracting").
Fix #2109
> Use fuzzy search for collections search

- aleph/manage.py
- aleph/tests/test_manage.py
- docker-compose.dev.yml
When running the tests (via `make test`), a certain ES Warning message pollutes the output of the `nosetests` execution. 
The Warning looks like this:
```
ElasticsearchWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.16/security-minimal-setup.html to enable security.
warnings.warn(message, category=ElasticsearchWarning)
```
In order to suppress this warning, I have added a the following environment variable setting to `docker-compose.dev.yml`: `xpack.security.enabled=false`. This should only be used in the development environment, for our convenience.
> Disable ES security in the development docker setup

- docker-compose.dev.yml
@monneyboi reported that the reloading feature of `flask run` wasn't properly working. I'm pretty sure it has to do with the debugger we are trying to attach. In either case [enabling earlier fails](https://flask.palletsprojects.com/en/2.1.x/server/#lazy-or-eager-loading) (instead of trying to fail lazily so a debugger can be shown) fixed the code reloading issue.
> Make code reloading work

- aleph/core.py
- aleph/migration.py
- aleph/tests/util.py
- aleph/views/archive_api.py
- aleph/views/base_api.py
- requirements.txt
The versions of the following packages were increased to the latest versions: `followthemoney`, `followthemoney-store`, `servicelayer`. Due to the fact that all 3 libraries use a newer version of `SQLAlchemy`, the versions of the following packages were also bumped to latest: `Flask`, `Flask-SQLAlchemy`, `SQLAlchemy`, `Flask-Babel`.
The commit also includes minor refactorings necessary as a result of these version bumps.
* `core.py` was refactored due to the `Flask-Babel` version bump [as per the docs](https://python-babel.github.io/flask-babel/#configuration)
* `migration.py`, `util.py` and `archive_api.py` were refactored due to the `SQLAlchemy` version bump
`archive.apy` was refactored as per [this interface change](https://github.com/pallets/flask/issues/4753)
> Bumps version of FTM libs, SQLAlchemy, Flask and related to latest

- aleph.env.tmpl
- requirements.txt
resolves https://github.com/alephdata/aleph/issues/3185
- ~bump version of servicelayer to include changes in https://github.com/alephdata/servicelayer/pull/99~
- add comment explaining that role-based auth is to be preferred over user-based, and that environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are only required for user-based auth.
> Enable IAM role-based auth between EC2 and S3

- contrib/email/generate_test_emails.py
This script allows you to easily generate RFC2822 messages with different structures for testing email ingestion and rendering in Aleph.
> Add simple script to generate test emails

- Makefile
- docker-compose.dev.yml
- docs/src/pages/developers/installation.mdx
- docs/src/pages/developers/technical-faq/index.mdx
I propose to use default ports for services, and to drop dejavu from the development setup as management software/gui would be up for personal preference.
I also removed the `hostname` params as they were the same as the defaults, plus bumped postgres to version 14.
> Clean dev environment

- aleph/index/util.py
- aleph/logic/alerts.py
- aleph/search/query.py
As passing the `fields` parameter to the ES highlight query breaks highlights https://github.com/alephdata/aleph/issues/3275, i propose removing this `query_string_query` function completely, as these dictionaries differ a bit, only occur in 3 locations, and just creating the query_string dictionaries on the spot is more understandable.
> Remove query_string_query function, remove fields from highlight query

- .github/workflows/pr.yml
This adds a pull-request "check" that will run `make format-check` to check if code from the PR is formatted correctly.
See https://github.com/alephdata/aleph/pull/3281
> Add `make format-check` as pull request "check"

- helm/charts/aleph/templates/api.yaml
- helm/charts/aleph/templates/ingest-file.yaml
- helm/charts/aleph/values.yaml
Updates:
* the apiVersion used for HorizontalPodAutoscaler from `autoscaling/v2beta1` to `autoscaling/v2`
* default Helm values configuration for API and Ingest-file HPAs
> #2998 autoscaling/v2 apiVersion for HorizontalPodAutoscaler

- docs/src/pages/users/faq/account/index.mdx
- docs/src/pages/users/getting-started/account/index.mdx
I have added notes at the top of the following two pages as they contain information specific to the Aleph instances operated by OCCRP. All other documentation pages should be generic.
> Add note to signup guide

- .github/workflows/docs.yml
We actually want individual docs PRs to trigger the build job. And we don’t care if there are multiple build jobs running at the same time. But we want there to be only one deploy job at the same time (in addition to the deploy job only being triggered manually or by pushes to the main branch).
> Limit concurrency of the deploy job only

- aleph/logic/html.py
- aleph/tests/test_view_util.py
This fixes a bug where Aleph doesn’t correctly preview HTML pages (see #3334).
The `etree.ElementTree.tostring` method stringifies as valid XML by default. While XML allows self-closing tags by default, only some tags can be self-closing in HTML.
This causes problems when rendering the sanitized HTML. Consider this example:
```html
<noscript><script src="..."></script></noscript>
<h1>Page title</h1>
<p>Some text</p>
```
When converting the sanitized element tree to XML, this would result in something like this:
```html
<noscript />
<h1>Page title</h1>
<p>Some text</p>
```
`noscript` is not a valid void element which results in browsers treating all following elements as children of the `noscript` tag, parsing the HTML into an effective DOM structure like this:
```html
<noscript>
<h1>Page …
```
> Stringify sanitized HTML as HTML (not XML)

- aleph/manage.py
Prevents existing collections from being renamed to the folder name when running crawldir. I haven't had the chance to test this but I've read over it and I don't think it will cause issues if merged
> Don't rename existing collections when running crawldir

- contrib/aleph-traefik-minio-keycloak/docker-compose.yml
- contrib/keycloak/docker-compose.dev-keycloak.yml
- docker-compose.yml
- helm/charts/aleph/values.yaml
This PR upgrades ingest-file to version 3.20.0 in Docker Compose and Helm config files.
> Upgrade to latest ingest-file release

- helm/examples/dev/README.md
The previous instructions simply don’t make sense 🙃
> Fix instructions on how to enable Prometheus in local Kubernetes cluster

- docs/src/pages/users/faq/account/index.mdx
Fixes a broken link in the user guide on this page: https://docs.aleph.occrp.org/users/faq/account/. We do automatically check for broken internal links in CI. While this link was supposed to be targeting another documentation page, it was an absolute URL and thus not detected by the broken link checker.
> Fix link target in user guide

- Dockerfile
- docs/src/pages/developers/alephclient.mdx
- docs/src/pages/developers/followthemoney/ftm.mdx
- docs/src/pages/developers/installation.mdx
I broke the default Dockerfile command in `7cfcb5`. While the Dockerfile did always specify the WSGI app `aleph.manage:app`, this has been incorrect for some time and it should have always been `aleph.wsgi:app`. Previously we never actually ran a container with the default command though and instead specified the command in the `docker-compose.yml` file. I removed the "duplicate" command in the `docker-compose.yml` in the referenced commit and thus the default command in the Dockerfile is now used.
I’ve now changed the default command specified in `Dockerfile` to be in line with the command previously set in `docker-compose.yml` (https://github.com/alephdata/aleph/blob/3.15.5/docker-compose.yml#L76).
* The WSGI app is now `aleph.wsgi:app` (this is specified in `gunicorn.py` not via a CLI …
> Fix default Dockerfile command

- CONTRIBUTING.md
- README.rst
- aleph/pages/about.en.md
- aleph/validation/spec.py
- docs/src/pages/developers/mappings.mdx
- helm/charts/aleph/README.md
- mappings/Makefile
- setup.py
- site/aleph.occrp.org/pages/faq.en.md
- ui/src/components/Collection/CollectionMappingsMode.jsx
- ui/src/components/Entity/EntityMappingMode.jsx
- ui/src/components/Investigation/InvestigationOverview.jsx
- ui/src/components/common/AppItem.jsx
When we updated the docs site, we set up redirects for all of these links, so they were still working, but it is time to properly update the links everywhere.
This also updates a few links to the user guide from within the Aleph UI, so I won’t merge this directly into `main` as I usually do with documentation changes, but instead follow the normal release process for code changes.
One of the CI workflows is currently failing -- I’ve fixed this in https://github.com/alephdata/aleph/pull/3670 and will rebase this branch as soon as the fix is merged.
> Fix documentation links

- ui/src/components/SearchField/util.js
Previously, the label for both email addresses and email entities was "Email" which could be confusing when both were displayed next to each other (for example on the dataset overview screen).
I’ve also updated the spelling from "E-Mail" to "Email" which seems to be the prevalent spelling of the term nowadays (and in other places in the UI).
Fixes #3668
> Change label for email address facets and statistics to remove ambiguity

- docs/src/pages/developers/technical-faq/index.mdx
Per https://github.com/alephdata/aleph/issues/3680#issuecomment-2057288614, I am attempting a pull request to remove references to the old `convert-document` container, which has since been consolidated into `ingest-file` (see https://github.com/alephdata/aleph/pull/2755).
This is my first pull request and I am open to learning! Please let me know if anything is wrong or if I need to make any adjustments.
> Remove references to convert-document

- docker-compose.yml
Something went wrong during the 3.15.5 release and as a consequence starting Aleph with the Docker Compose configuration from the main branch doesn’t work. Once we’ve published a fixed release we can remove this line again.
For context: The line was removed in [this commit](https://github.com/alephdata/aleph/commit/e5eba0d0a6d63ae5ff7b813b3e50fcad7b570e21#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3) which is on the `main` branch. But the commit never ended up in the 3.15.5 release. That means that `docker-compose.yml` on `main` is currently not in line with the configuration required to run 3.15.5 (the most recent release).
This PR basically restores `docker-compose.yml` on `main` to be inline with the required configuration to run `3.15.5`: …
> Temporarily roll back changes to Docker Compose config

- .github/dependabot.yml
- Makefile
- e2e/Dockerfile
- e2e/requirements.txt
- requirements-dev.txt
So far the situation with e2e tests was that both the Dockerfile and the requirements mentioned playwright versions, but due to the way Dependabot works it can't update them atomically. Getting out-of-sync versions would result in failed e2e tests.
This change proposes keeping the version in one place and automatically pulling the corresponding container image version based on that.
It also moves e2e-related dependencies from `requirements-dev.txt` to `e2e/requirements.txt` and updates the dependabot configuration accordingly.
> Keep Playwright versions in sync

- aleph/core.py
> Use default language when Accept-Language header is '*'

- .github/workflows/discourse.yml
This is based on https://github.com/roots/discourse-topic-github-release-action
> Automatically post releases to Discourse

- aleph/worker.py
After I failed to implement this in a generic way for all workers in https://github.com/alephdata/servicelayer/pull/173 here's an attempt to make Aleph register a timer which continuously polls for periodic tasks to be run.
> Register a timer which runs periodic tasks

- .github/workflows/e2e.yml
- Makefile
The `docker compose run` command doesn’t support the `--build-arg` argument. Depending on the Docker Compose version installed, using the `--build-arg` argument would either exit with an error code or simply print the command help.
To achieve the desired outcome, we can first build the image with the build argument, then start the container. This has the additional advantage of separating the build logs from the logs of the actual command execution in the GitHub Actions UI.
Tested these changes: https://github.com/alephdata/aleph/actions/runs/9205541034/job/25321430312
> Fix end-to-end tests in CI

- aleph/worker.py
This hotfix addresses the following stacktrace:
```
Traceback (most recent call last):
File "/aleph/aleph/worker.py", line 146, in periodic
self.run_indexing_batches()
File "/aleph/aleph/worker.py", line 208, in run_indexing_batches
op_index(collection_id, batch, worker=self)
File "/aleph/aleph/worker.py", line 45, in op_index
index_many(collection, sync=sync, tasks=batch)
File "/aleph/aleph/logic/processing.py", line 22, in index_many
aggregator = get_aggregator(collection)
File "/aleph/aleph/logic/aggregator.py", line 14, in get_aggregator
dataset = get_aggregator_name(collection)
File "/aleph/aleph/logic/aggregator.py", line 9, in get_aggregator_name
return "collection_%s" % collection.id
AttributeError: 'NoneType' object has no attribute 'id'"
```
> Exit op_index early in Aleph Worker

- aleph/model/__init__.py
- aleph/model/role.py
- aleph/oauth.py
- aleph/settings.py
- aleph/tests/test_sessions_api.py
- aleph/tests/util.py
- aleph/views/base_api.py
- aleph/views/sessions_api.py
- ui/src/components/common/RoleBlockedMessage.tsx
- ui/src/components/common/index.jsx
- ui/src/dialogs/AuthenticationDialog/AuthenticationDialog.jsx
- ui/src/screens/OAuthScreen/OAuthScreen.jsx
Aleph includes an option to block individual users. Blocking users effectively makes it impossible for them to sign in. Right now, a generic authentication failure message is displayed when a blocked user tries to sign in. As we’re considering blocking user accounts that have been inactive for some time, we want to display a specific error message (incl. instructions on how to reactivate the account) when a user has been blocked.
* Most of the diff in this PR comes from new tests for the existing password and OAuth authentication flows.
* The new test cases for the OAuth flow are as close the the real flow as possible, only mocking one request to the identity provider to fetch OAuth tokens.
* The main change in the actual authentication logic is a refactoring: Before, both the password …
> Display an error message for blocked users

- aleph/worker.py
- ui/src/screens/SystemStatusScreen/SystemStatusScreen.jsx
- ui/src/screens/SystemStatusScreen/SystemStatusScreen.scss
This exposes the two timestamps (that are already returned per collection by the status API) in the UI. Times are relative (for example "45 seconds ago"), but hovering over them displays the full date/time (for example "Fri, Jun 28, 2024, 5:05 PM").
**Todos:**
> Display start and last updated timestamp on system status page

- ui/src/dialogs/CollectionAccessDialog/CollectionAccessDialog.jsx
The reason behind excluding specific IDs is to not suggest users and groups that are already associated with the collection. However, the `/roles/_suggest` endpoint returns only users, never groups, so there is no point in explicitly excluding groups. Fixes #3820.
In case a collection is shared with a large (200+) number of individual users, this may cause the same error as reported in #3820. However, this would require explicitly sharing a collection with such a large number of users whereas #3820 affected any collection, even if it wasn’t shared with anyone. Also, I don’t think there has been a use case for sharing a collection with so many individual users, and probably using groups would be more appropriate in such a situation.
You can verify this by adding yourself to a few user …
> Fix user auto-suggest input / do not explicitly exclude group IDs 

- docs/src/options.json
- docs/src/pages/developers/getting-started/production-deployment/docker-compose/index.mdx
- docs/src/pages/developers/getting-started/production-deployment/index.mdx
- docs/src/pages/developers/how-to/data/export-mentions/index.mdx
- docs/src/pages/developers/how-to/operations/users-and-groups/index.mdx
- docs/src/pages/developers/reference/configuration-options/options.yml
- docs/src/pages/users/search/advanced/index.mdx
This PR contains a few small documentation enhancements as follow-ups to #3064. The changes are mostly informed by bug reports/questions from users and admins. For details, see the commit messages.
> Misc documentation enhancements

- aleph/authz.py
- aleph/metrics/collectors.py
- aleph/metrics/exporter.py
- aleph/metrics/flask.py
- aleph/tests/test_entities_api.py
- aleph/tests/test_metrics.py
- aleph/views/context.py
- aleph/views/sessions_api.py
- requirements.txt
This PR adds a few new metrics and extends existing metrics based on feedback. I’d recommend taking a look at the individual commits when reviewing this PR.
Corresponding documentation changes are in #3845 because the `release/4.0.0` branch doesn’t yet have the recently updated tech docs from `develop`.
I’ve added new `active` and `locale` labels to the `aleph_users` metric. This allows querying for the number of active users (e.g. within last 24h, 7d, 30d, …) and the number of users that use a specific UI locale.
```
aleph_users{active="all"}
aleph_users{locale="en", active="all"}
aleph_users{active="30d", locale="de"}
```
Previously, there was a single `aleph_collections` metric that allowed querying for the number of collections by category (e.g. "casefile", "leak", "gazette", …). I …
> New and updated Prometheus metrics

- aleph/tests/test_entities_api.py
This test started to fail with an upgrade of the `phonenumbers` package (imported via `followthemoney`) which included updated phone number validation rules. As a result, the phone numbers in this test case didn’t pass validation anymore and were cleaned from the entites created.
At first glance these numbers seemed to be valid German mobile phone numbers and I was worried that there might be a regression in `phonenumbers`. But according to the International Telecommunication Union, a phone number with the prefix `176` has to be 11 digits long. I adjusted the tests accordingly.
https://www.itu.int/oth/T0202000051/en
> Fix phone numbers used in tests

- aleph/metrics/collectors.py
- aleph/migrate/versions/8adf50aadcb0_add_last_login_at_column.py
- aleph/model/role.py
- aleph/tests/test_metrics.py
- aleph/tests/test_sessions_api.py
- aleph/views/sessions_api.py
When implementing the active users metric (#3844), I noticed that Aleph currently updates the `role.updated_at` column every time a user logs in – so I took the shortcut and simply used that to count the number of users that logged in at least once within a specific period of time. But it turns out that `updated_at` is only updated on login when using password auth. It isn’t updated when signing in via OAuth, and consequently the active users metric is incorrect when OAuth is used for authentication.
I’m fixing this by adding a separate timestamp column that stores when a user last logged in. It’s probably a good idea to make the intent clear (Just reading the name updated_at, most people probably wouldn’t expect that timestamp to be set every time a user logs in.)
Note: This currently …
> Fix active users metric

- aleph/metrics/collectors.py
- aleph/tests/test_metrics.py
This bug occurred due to a combination of two edge cases:
1. The Python Prometheus client does allow `None` as a label value, except when implementing a custom collector[1] which we are doing in this case. If you try to use `None` as a label value when implementing a custom collector, everything will work fine just until the metrics are actually exposed (for example when Prometheus sends a request to the `/metrics` endpoint) which will raise an unhandled exception.
2. In Aleph, every collection can be assigned zero or more countries and languages. These are stored as array columns in Postgres. For example, if a collection contains data about Germany and Luxembourg, that would be stored as `{de,lu}`. However, in real-life, we also have a few collections with `{NULL}` (instead of just an …
> Fix edge cases in custom metrics

- aleph/tests/test_permissions_api.py
- aleph/tests/test_roles_api.py
- aleph/validation/schema/permission.yml
- aleph/views/permissions_api.py
- aleph/views/roles_api.py
- ui/src/components/common/Role.jsx
- ui/src/dialogs/CollectionAccessDialog/CollectionAccessDialog.jsx
This enables sharing of investigations with individual users by providing their full email address. Main changes are in 7cced50eaa0ff09eca17dba5c977c9b6814ac6c7.
If you want to manually test cases including OAuth user groups, you can set up Keycloak in your development environment like this: https://docs.aleph.occrp.org/developers/how-to/development/identity-provider/
> Allow sharing of investigations

- aleph/tests/test_permissions_api.py
- aleph/views/permissions_api.py
- ui/src/components/common/Role.jsx
This PR fixes a few small UX bugs related to investigation sharing and user suggestions:
* Previously, when clearing the input field for user suggestions, the old suggestions for the previous value were still displayed.
* Email addresses weren’t properly normalized, so ` john.doe@example.org` (leading whitespace) or `JOHN.DOE@example.org` wouldn’t match `john.doe@example.org`.
* Due to a bug in the underlying Blueprint component library, we were sending duplicate calls to the suggestions API endpoint on every keystroke.
> Multiple small UX enhancements related to investigation sharing/user suggestion component

- aleph/metrics/collectors.py
- aleph/tests/test_metrics.py
For some reason, the default/fallback value returned by `get_collection_stats` is an empty list, not an empty object. This can trigger an edge case if Prometheus metrics are scraped after a collection has been created, but the stats for the new collection haven’t been computed yet.
To prevent unintended side effects, I haven’t changed the default/fallback value (as other parts of the code base might rely on it) and have instead explicitly handled empty values.
> Fix edge case in metrics collector

- site/aleph.occrp.org/pages/faq.en.md
This updates two broken docs links in the FAQ on aleph.occrp.org.
> Update documentation links in FAQ

- aleph/tests/test_sessions_api.py
This is a follow-up to https://github.com/alephdata/aleph/pull/3852. This PR above didn’t include a test for the expected behavior when logging in via OAuth. There have been a lot of changes to authentication testing on the develop branch that were not present in the 4.0 release branch, so any changes would have lead to annoying merge conflicts down the line.
But now that the 4.0 release is integrated, it’s time to add a proper test :)
> Add test to cover `last_login_at` timestamp in OAuth workflow

- ui/src/viewers/PdfViewerSearch.jsx
When searching a large document in a dataset which has a significant number of results, only the first set of results are shown.
I’ve fixed this by implementing infinite scrolling in the same way we already implement this for other views (such as the main search view). Now, when a user has scrolled to the end of the search results list and if there are more results, the next page of results is automatically loaded.
In addition, I’ve used the opportunity to do some cleanup and remove dead code from the component responsible for displaying document search results.
> Implement infinite scrolling for document search

- docker-compose.e2e.yml
This was added to fix a broken test, but its best left unset (to test the default value).
> undo e2e setting

- ui/src/app/Router.jsx
- ui/src/app/Router.scss
Fixes #3812. Previously, the UI would retry the metadata request indefinitely and without a delay. Now, if the metadata request fails, an error message and a button to reload the page are displayed.
I haven’t implemented automatic retries with back-offs for now, as this adds complexity and I’m not sure it’s necessary.
> Fix infinite request loop if metadata request fails

- Makefile
Small improvement, but I need this! No more sleep! 😳
> Use pg_isready in make upgrade instead of sleep

- aleph/migrate/versions/131674bde902_add_primary_key_constraint_to_role_membership.py
- aleph/model/role.py
- aleph/tests/test_sessions_api.py
Aleph users can be part of user groups. Users and groups are both modeled as "roles" in Aleph. To add a user to a group, a row is inserted into the `role_membership` table.
We’ve occasionally had issues with duplicate rows in this table, likely due to a race condition when Aleph handles parallel OAuth requests for the same user (https://github.com/alephdata/aleph/issues/3811#issuecomment-2232953036), but we haven’t been able to reproduce or pinpoint the exact root cause.
The effect of a duplicate role membership is that users are permanently blocked from authenticating until the duplicates are removed.
This PR adds a primary key constraint to the `role_membership` table. While this does not address the root cause of the problem, it prevents duplicates from being inserted into the table. …
> Do not allow duplicate role memberships

- ui/src/components/Document/DocumentViewMode.scss
- ui/src/components/Entity/EntityPreview.scss
- ui/src/components/Entity/EntityViews.jsx
- ui/src/components/Entity/EntityViews.scss
- ui/src/components/common/ItemOverview.scss
- ui/src/util/togglePreview.js
- ui/src/viewers/PdfViewer.jsx
- ui/src/viewers/PdfViewer.scss
- ui/src/viewers/PdfViewerSearch.jsx
- ui/src/viewers/PdfViewerSearch.scss
We frequently receive feedback about the search flow requiring too many clicks in the following use case:
1. User searches for a term.
2. User finds a document (e.g. PDF, Word) that might be relevant in the search results.
3. They click on the search results and the preview is displayed.
4. In case of documents that are longer than a few pages, most users don’t want to go over the entire document, instead they want to skim the relevant sections.
5. In order to find relevant sections, users currently need to click on the "Expand" button in the entity preview. After clicking expand, the document search is available.
7. Users then need to enter the search term again in the document search input.
This PR simplifies this flow as the document search is now available from within the entity …
> Make document search available in entity preview

- helm/charts/aleph/templates/exporter.yaml
- helm/charts/aleph/values.yaml
Generating all metrics can take multiple seconds for large Aleph instances, which can make the liveness/readiness probe fail. The `name[]` query parameter can be used to select a subset of metrics the exporter should return (or no metrics as all in this case). That way, we can check that the exporter is up and running without actually generating any metrics.
> Update Prometheus exporter probes so they do not actually generate all metrics

- ui/src/app/Router.jsx
Fixes #3999.
This is related to #3948 in which I fixed the infinite request loop in case requests to the metadata API fail. This works as intended, but has one unintended side effect: We were actually kind of relying on the previous behavior to handle expired session tokens.
For context: When a user logs in, the session token is stored. When the session token expires, future API requests using that session token will obviously fail. The UI was previously handling 401 response codes to invalidate the stored session token and display a login popup or redirect to the OAuth service.
The change introduced in #3948 also prevented the handling of requests that failed to expired session tokens. I’m not convinced that this way of handling expired session tokens is a good solution as it’s pretty …
> Show login popup or redirect to OAuth provider when session token has expired

- ui/src/screens/EntitySetIndexScreen/EntitySetIndexScreen.jsx
It would send a sort order of "created_at ASC", but in the backend it does:
q.order_by(EntitySet.updated_at.desc())
So that defaultSortBy() doesn't really do anything. Could perhaps remove that backend check; I just left it in for now.
This improves compatibility with Alfred as it doesn't have this hard-coded in the backend and just uses the URL.
> Send correct sort order when listing entitysets

- ui/src/components/common/DeleteDialog.tsx
When deleting a dataset or investigation you have to type in the name of it to confirm. I typically just copy the name, but it's easy to copy an extra space. Don't be too anal about all of this.
> More relaxed check when deleting objects

- contrib/aleph-traefik-minio-keycloak/docker-compose.yml
- contrib/keycloak/docker-compose.dev-keycloak.yml
- docker-compose.yml
- helm/charts/aleph/README.md
This should fix #4001 , which probably broke during a merge.
> Fix docker-compose image tax syntax

- ui/src/components/Dashboard/Dashboard.jsx
Previously it was inconsistent: "Alerts", "Exports", and "Investigations" would always display "0" if there's nothing, and the entitysets (Network diagrams etc.) didn't display anything.
> Always display "0" in dashboard if there are no entities

- aleph/logic/api_keys.py
- aleph/logic/util.py
- aleph/manage.py
- aleph/migrate/versions/31e24765dee3_add_api_key_digest_column.py
- aleph/model/role.py
- aleph/tests/test_api_keys.py
- aleph/tests/test_role_model.py
- aleph/tests/test_view_context.py
- aleph/views/reconcile_api.py
This is based on #3094. Review and merge #3094 first!
***
Aleph used to store user API keys as plaintext in the database. This commit changes that to store only a hash of the API key.
API keys are generated using the built-in `secrets.token_urlsafe` method which returns a random 256 bit token. In contrast to passwords, API keys are not provided by users, have a high entropy, and need to be validated on every request. It seems to be generally accepted that, given 256 bit tokens, salting or using an expensive key derivation functions isn't necessary. (But please challenge this!) For this reason, we’re storing an unsalted SHA-256 hash of the API key which also makes it easy to look up and verify a given API key.
I've added a separate column for the hashed API key rather than reusing the …
> Hash API keys

- .github/workflows/build-ui.yml
- ui/package-lock.json
- ui/package.json
We previously skipped this step as it can take quite long (due to the outdated CRA build setup), but some errors will only occur during a final build (e.g. missing type declarations in dependencies).
> Build UI for every commit/PR

- aleph/settings.py
The API_RATE_WINDOW variable was hardcoded to 15 minutes and not sourced from environment. This commit fixes this bug.
> Source API_RATE_WINDOW from environment

- .github/ISSUE_TEMPLATE/config.yml
At the moment when someone wants to open a new issue in this repo they get this chooser:
This is still the first place people come to when they need help with their Aleph setup, but we'd rather have support issues (and discussions in general) in our Discourse and only stick to having only the issues and feature requests we actively want to work on here on Github.
I propose two changes:
- disable the blank issue link
- link to our community Discourse and encourage people to get support over there
I made the changes based on [these docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser).
> Disable blank issues and link to Discourse

- aleph/model/role.py
- aleph/tests/test_view_context.py
These additional checks aren't necessary in theory (and we do already have tests covering these edge cases), but I think they still make sense to make them explicit and to be more resilient against potential future changes.
> Add additional validation checks

- aleph/logic/api_keys.py
- aleph/tests/test_api_keys.py
The `api_key` column will be removed in the next version at which point all plaintext API keys will be deleted.
> Do not delete API key to enable rollbacks to previous version.

- aleph.env.tmpl
`ingest-file` [uses](https://github.com/alephdata/ingest-file/blob/c014ac985d5804f3850ea6aca41d34519c293f66/ingestors/support/cache.py#L15) the [Tags functionality from servicelayer](https://github.com/alephdata/servicelayer/blob/b2076808c26efdedbd7f2fca92fba02e2d7f8383/servicelayer/tags.py#L19) to cache certain document types during ingest to speed up its operation. Normally the settings file defaults to trying the ALEPH_DATABASE_URI followed by the FTM_STORE_URI, which in most cases should be set to non-default values.
But if one were to just follow our prod environment docs blindly and not uncomment these two settings then the TAGS_DATABASE_URI would be unset, causing servicelayer to pick the default (sqlite:///) which breaks now that we have multiple threads writing to the tags …
> Point out use of TAGS_DATABASE_URI and how it works

- aleph.env.tmpl
ingest-file uses the Tags functionality from servicelayer to cache certain document types during ingest to speed up its operation. Normally the settings file defaults to trying the ALEPH_DATABASE_URI followed by the FTM_STORE_URI, which in most cases should be set to non-default values.
But if one were to just follow our prod environment docs blindly and not uncomment these two settings then the TAGS_DATABASE_URI would be unset, causing servicelayer to pick the default (sqlite:///) which breaks now that we have multiple threads writing to the tags database.
This change documents how this setting works and encourages one to set it if the above two settings are left to defaults.
Relates to #4002, #3816
> bugfix: Point out use of Tags db and how it works

- aleph/worker.py
The `prefetch_settings` were never passed to the servicelayer worker constructor so the calculation of the `max_size` of the local queue in the worker was always returning 1. Which is generally fine, until it's not. This is only a problem for deployments with a separate index worker.
> fix: incorrect local queue size calculation

- helm/charts/aleph/templates/aleph-upgrade-job.yaml
- helm/charts/aleph/templates/api.yaml
- helm/charts/aleph/templates/exporter.yaml
- helm/charts/aleph/templates/worker-index.yaml
- helm/charts/aleph/templates/worker.yaml
This PR mounts new secret for Aleph with environmental variable. It contains a password for a new notification system (kuvert).
> migrate aleph notification to k8s with kuvert

- ui/src/components/AuthButtons/AuthButtons.scss
- ui/src/components/common/Summary.jsx
- ui/src/components/common/Summary.scss
This fixes two issues with summaries/descriptions of datasets and entity sets:
1. Long summaries weren’t properly truncated, the overflow wasn’t hidden. I introduced this regression in #4057.
3. In listings of datasets and entity sets, Markdown was rendered (including block-level elements such as lists). This is a regression that was introduced a long time ago with a dependency update of `react-markdown`.
> Fix rendering of dataset summaries
