- Makefile
> Add SASS_PATH for asset making

- aleph/search/facets.py
Only return aggregation counts for collections the user can read. Fixes #92
> Filter readable collections after aggregation

- .dockerignore
- .gitignore
- .travis.yml
- Dockerfile
- Makefile
- aleph/manage.py
- contrib/base/Dockerfile
- docker-compose.yml
- docs/installation.md
- requirements.txt
Some suggestions and notes I tried to document or simplify while working on Aleph.
There's a new installation guide I would like to get some feedback on.
I also tried to simplify the dockerfiles where possible and reduce the footprint of running Aleph containers.
Following the guide, getting started with a local development instance now should be much easier and clear.
/cc @pudo
> Simplified setup and docs

- aleph/static/js/aleph.js
- aleph/static/js/controllers/TabularCtrl.js
- aleph/static/js/loaders/loadTabular.js
@pudo here are some minor fixes to review after the merge with the new asset pipeline.
Thanks in advance.
> Fixed minor typos and imports for tabular view support.

- .travis.yml
- Makefile
- aleph/__init__.py
- aleph/core.py
- aleph/index/__init__.py
- aleph/index/entities.py
- aleph/manage.py
- aleph/model/role.py
- aleph/templates/layout.html
- aleph/tests/factories/models/__init__.py
- aleph/tests/factories/models/collection.py
- aleph/tests/factories/models/entity.py
- aleph/tests/test_models.py
- aleph/tests/util.py
- docker-compose.yml
- requirements-testing.txt
- requirements.txt
- test_settings.py.tmpl
This needs to be merged only after #118 is closed.
It covers a note from the wiki related to #119 
https://github.com/pudo/aleph/wiki/Maintenance#deleting-all-pending-entities
I tried adding a test for this change and it looks like all the fixtures require manual composition.
I suggest using factories and fake generators to build these for further tests.
This is superior since it abstracts the interaction with models to the minimum necessity and brings a decent randomness aspect that can make the tests more solid.
@pudo let me know what are your thoughts on this.
> Docs missing cmds

- aleph/data/parse.py
- aleph/tests/data/test_parse.py
- docs/installation.md
- requirements.txt
This should fix issues reported in #126  and (hopefully) #125 
@pudo please take a look when you have some time.
Ty in advance!
> Sans dateparser

- aleph/schema.yaml
Added FBiH jibCode and mbsCode to Company and ownershipType to ownedBy link
> New company and ownedBy props

- aleph/tests/test_view_util.py
- aleph/views/util.py
A follow on to #231, remove the old method and broken tests
> Remove extract_next_url

- Makefile
- aleph/index/documents.py
- aleph/index/entities.py
- aleph/index/util.py
- aleph/logic/alerts.py
- aleph/logic/entities.py
- aleph/logic/roles.py
- aleph/model/metadata.py
- aleph/search/result.py
- aleph/tests/test_documents_api.py
- aleph/views/ingest_api.py
- aleph/views/roles_api.py
- aleph/views/serializers.py
- aleph/views/util.py
- requirements.txt
Nothing special here, gonna merge when tests pass.
> Cleanup roles and document indexer.

- ui/package.json
- ui/src/actions/asyncActionCreator.js
- ui/src/actions/index.js
- ui/src/actions/sessionActions.js
- ui/src/app/App.jsx
- ui/src/app/api.js
- ui/src/components/CollectionScreen/CollectionInfo.jsx
- ui/src/components/CollectionScreen/index.jsx
- ui/src/components/DocumentScreen/index.jsx
- ui/src/components/DocumentScreen/viewers/FolderViewer.jsx
- ui/src/components/EntityScreen/index.jsx
- ui/src/components/HomeScreen/HomeContent.jsx
- ui/src/components/SearchScreen/SearchFilter.jsx
- ui/src/components/SearchScreen/SearchResultList.jsx
- ui/src/components/SearchScreen/SearchResultListItem.jsx
- ui/src/components/SearchScreen/index.jsx
- ui/src/reducers/collections.js
- ui/src/reducers/documentCache.js
- ui/src/reducers/documentChildrenResults.js
- ui/src/reducers/entityCache.js
- ui/src/reducers/metadata.js
- ui/src/reducers/search.js
- ui/src/reducers/session.js
- ui/src/reducers/util.js
- ui/src/util/getPath.js
Mostly just refactoring the actions and reducers for maintainability.
> Clean up UI logic

- ui/src/components/ProfileScreen/AlertsPane.jsx
- ui/src/components/auth/AuthButtons.jsx
- ui/src/components/auth/AuthButtons.scss
> fixed navbar settings icon and search alerts

- ui/src/components/CollectionScreen/CollectionInfo.jsx
- ui/src/components/CollectionScreen/index.jsx
- ui/src/components/EntityTable/EntityTable.jsx
- ui/src/components/SettingsButton/SettingsButton.jsx
- ui/src/components/auth/LoginScreen.jsx
- ui/src/components/auth/PasswordAuth.jsx
- ui/src/components/auth/SignIn.scss
- ui/src/components/auth/SignupScreen.jsx
- ui/src/components/common/Collection/CollectionInfo.jsx
- ui/src/dialogs/CollectionEditDialog/index.jsx
- ui/src/screens/CollectionsIndexScreen/CollectionsIndexScreen.jsx
- ui/src/screens/HomeScreen/HomeScreen.jsx
- ui/src/screens/HomeScreen/index.jsx
- ui/src/screens/SearchScreen/SearchScreen.jsx
- changes all labels from 'collections' to 'sources'
- added navbar to login and signup screen
- centered login and signup screen
> Emina collection source

- ui/src/components/Preview/Preview.jsx
- ui/src/reducers/collections.js
- ui/src/screens/CollectionScreen/index.jsx
- adding status to error when fetching
> fixing hack for authorization error

- ui/src/dialogs/AccessCollectionDialog/AccessCollectionDialog.jsx
- fixed bug regarding checkboxes on permissions for collection
> Bug #395: Cannot remove permissions in access dialog 

- ui/src/app/App.scss
- ui/src/components/DocumentViewer/TableViewer.jsx
- ui/src/components/DocumentViewer/TableViewer.scss
> Use blueprint table viewer

- ui/src/actions/collectionActions.js
- ui/src/actions/index.js
- ui/src/components/Collection/CollectionToolbar.jsx
- ui/src/components/Collection/CollectionXrefAlert.jsx
- ui/src/reducers/collectionXrefMatches.js
> Cross-reference button

- ui/src/components/Navbar/Navbar.jsx
- ui/src/components/Toolbar/DownloadButton.jsx
- ui/src/components/common/Category.jsx
- ui/src/components/common/Collection.jsx
- ui/src/components/common/Count.jsx
- ui/src/components/common/Country.jsx
- ui/src/components/common/Entity.jsx
- ui/src/components/common/ErrorSection.jsx
- ui/src/components/common/FileSize.jsx
- ui/src/components/common/Language.jsx
- ui/src/components/common/Schema.jsx
- ui/src/components/common/Tag.jsx
- ui/src/components/common/URL.jsx
- changed onclick events on buttons by using Link component
> Link fixes

- ui/src/components/Collection/CollectionToolbar.jsx
- ui/src/components/common/Date.jsx
Implements 
- [8.] from #513 _Change date format, for example 2016-07-14 becomes 14 July 2017_
- Changed label '**Access**' to '**Share**' in `CollectionToolbar`
> Small ui improvements 

- ui/package.json
- ui/src/app/App.scss
- ui/src/app/blueprint-overrides.scss
- ui/src/components/Collection/CollectionViews.jsx
- ui/src/components/Document/DocumentViews.jsx
- ui/src/components/Footer/Footer.jsx
- ui/src/components/Footer/Footer.scss
- ui/src/components/common/Icon.jsx
- ui/src/components/common/Icon.scss
- ui/src/components/common/Role.jsx
- ui/src/components/common/Schema.jsx
- ui/src/components/common/Tag.jsx
- ui/src/components/common/Tag.scss
- ui/src/components/common/URL.jsx
> Replaced font-awesome icons

- ui/src/app/App.scss
- ui/src/app/tables.scss
- ui/src/components/EntityTable/EntityTable.jsx
- ui/src/components/EntityTable/EntityTable.scss
- ui/src/components/EntityTable/EntityTableRow.jsx
- ui/src/components/common/Date.jsx
- ui/src/components/common/Entity.jsx
- ui/src/components/common/Icon.scss
- ui/src/components/common/Property.jsx
- ui/src/components/common/Schema.jsx
- ui/src/components/common/TextLoading.jsx
- ui/src/screens/HomeScreen/HomeScreen.jsx
- ui/src/screens/SearchScreen/SearchScreen.jsx
> Highlighted sentences on search

- ui/src/screens/CasesIndexScreen/CasesIndexScreen.jsx
- ui/src/screens/CasesIndexScreen/CasesIndexScreen.scss
Polishing 'New case' button on Case screen. 
For more details see #569
> CaseScreen 'New case' btn polish

- ui/src/followthemoney/schema.ts
The logic of entity property visualisation was working wrong[After FtM integration].
Thanks @uhhhuh for report!
> Small fix on entity properties visualisation

- ui/src/actions/sessionActions.js
- ui/src/app/App.jsx
- ui/src/dialogs/AuthenticationDialog/AuthenticationDialog.jsx
show an error message when user enters an invalid username or password
> Login Error Handling

- aleph/index/match.py
- aleph/logic/xref.py
- aleph/manage.py
- aleph/tests/test_xref.py
add -a / --against flag to xref xli command for selective xref
> #572 Make Xref more specific

- aleph/settings.py
Let users make a choice of UI language configuration similar to Languages.
> Make UI languages configurable

- requirements-toolkit.txt
- ui/src/actions/collectionActions.js
- ui/src/actions/index.js
- ui/src/components/Collection/CollectionAnalyzeAlert.jsx
- ui/src/components/Collection/CollectionToolbar.jsx
- ui/src/dialogs/CollectionDeleteDialog/CollectionDeleteDialog.jsx
* Moved collection actions to a drop-down.
* Added a new `re-analyze` action.
* Added `Delete` button to the dropdown
> Collection actions as dropdown

- ui/src/actions/documentActions.js
- ui/src/components/Collection/CollectionOverview.jsx
- ui/src/components/Document/DocumentViewMode.jsx
- ui/src/components/Entity/EntityInfoMode.jsx
- ui/src/components/Navbar/Navbar.jsx
- ui/src/components/Toolbar/CloseButton.jsx
- ui/src/queries.js
- ui/src/screens/SearchScreen/SearchScreen.jsx
- ui/src/viewers/PdfViewer.jsx
- ui/src/viewers/TextViewer.jsx
1. death code cleanup
2. Collection Screen stabilisation
3. Intro-document search recovery
4. Preview sidebar fix
5. Unused facets removal
6. PdfViewer text mode thru /content'
7. SearchBox <--> URL binding
~8. Graceful degradation on EntityInfoPanel~
8. Added collection info in EntityInfoPanel
> v3 ui improvements

- ui/package.json
- ui/src/components/Entity/EntityReferencesMode.jsx
- ui/src/components/QueryTags/QueryFilterTag.scss
- ui/src/components/common/Count.jsx
- ui/src/components/common/SignInCallout.scss
- ui/src/screens/HomeScreen/HomeScreen.jsx
- ui/src/screens/HomeScreen/HomeScreen.scss
* Deny relative imports
* Showing user-roles in home page. described in 8th point of #625
* Fixed 'count 0' issue in HomePage
> UI updates

- ui/src/components/Document/DocumentScreenContext.jsx
- ui/src/components/Entity/EntityReferencesMode.jsx
- ui/src/components/common/Breadcrumbs.jsx
- ui/src/components/common/SearchBox.jsx
- ui/src/components/common/index.jsx
* Fixeq query persisting issue in the search box
* Better components organising
> Searching for references

- ui/src/viewers/EmailViewer.jsx
> Email viewer bug fixed

- ui/package.json
we are basically upgrading the `react-helmet` to `v6b` for details see https://github.com/nfl/react-helmet/issues/373
> Fixes stack-overflow issue occured by react-helmet

- aleph/views/context.py
X-Content-Type-Options: nosniff
> add http header X-Content-Type-Options: nosniff

- ui/package.json
- ui/src/components/Document/DocumentViewMode.jsx
- ui/src/viewers/CsvStreamViewer.jsx
> Streaming CSV viewer

- requirements-toolkit.txt
- services/ingest-file/requirements.txt
Botched 3.2.6 because of overnight dependency change.
> Aleph 3.2.7

- aleph/analysis/extract.py
- requirements-generic.txt
This PR uses the official fasttext package for language detection and fixes bug #750 .
> use fasttext, bugfix lang detection

- aleph/index/entities.py
- aleph/index/indexes.py
- aleph/index/util.py
- aleph/search/__init__.py
- aleph/search/query.py
- services/elasticsearch/Dockerfile
- ui/src/components/Collection/CollectionIndexSearch.jsx
Fixes #724. Depends on https://github.com/alephdata/followthemoney/pull/54
> Cast dates and numeric properties into a numeric field in ES 

- ui/src/components/common/Breadcrumbs.scss
Removed blue background from page breadcrumbs
> Make breadcrumbs plain, not blue

- aleph/oauth.py
- aleph/views/sessions_api.py
Fixes #868 
Here are my OAuth settings:
```
ALEPH_OAUTH_NAME='google'
ALEPH_OAUTH_KEY=xxx
ALEPH_OAUTH_SECRET=xxx
ALEPH_OAUTH_SCOPE='openid email profile'
ALEPH_OAUTH_BASE_URL='https://www.googleapis.com/oauth2/v2/'
ALEPH_OAUTH_TOKEN_URL='https://www.googleapis.com/oauth2/v4/token')
ALEPH_OAUTH_AUTHORIZE_URL='https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent'
```
> Fix Google OAuth login

- ui/package.json
- ui/src/app/App.scss
- ui/src/components/Collection/CollectionHeading.jsx
- ui/src/components/Collection/CollectionListItem.jsx
- ui/src/components/Collection/CollectionListItem.scss
- ui/src/components/Entity/EntityInfoMode.jsx
- ui/src/components/common/Collection.jsx
- ui/src/components/common/DualPane.scss
> Support Markdown in Collection Summaries

- ui/src/app/blueprint-overrides.scss
- ui/src/components/Navbar/Navbar.jsx
- ui/src/components/Navbar/Navbar.scss
- ui/src/components/Notification/Notification.scss
- ui/src/components/Property/Property.scss
- ui/src/components/Screen/Screen.jsx
- ui/src/components/SearchTips/SearchTips.jsx
- ui/src/components/Toolbar/DownloadButton.jsx
- ui/src/components/common/Breadcrumbs.scss
- ui/src/components/common/DualPane.scss
- Fixes Search Tips toggle issue, and allows for interaction with search bar while tips are open
- Fixes Entity/CollectionView tab list horizontal overflow issue
- Aligns Navbar and Breadcrumb horizontal padding
- Fixes Breadcrumb small-screen foldup 
- Hover styling for "mention" property links
- Fixes vertical mis-alignment of entity labels and text in Notifications/Search results
> Small UI Fixes

- ui/src/components/Toolbar/PagingButtons.jsx
- ui/src/components/Toolbar/PagingButtons.scss
- ui/src/viewers/PdfViewer.jsx
Resolves #943 
- Rotation buttons for PDF Viewer
- Page numeric input for PDF Viewer
> Document PDF Viewer - Rotation & Page Input Controls

- aleph/index/entities.py
- aleph/search/query.py
- aleph/tests/test_entities_api.py
> Fix sorting by date

- ui/src/app/variables.scss
- ui/src/components/Collection/CollectionContentViews.scss
- ui/src/components/Collection/CollectionInfo.jsx
- ui/src/components/Collection/CollectionInfo.scss
- ui/src/components/Collection/CollectionListItem.jsx
- ui/src/components/Document/DocumentManager.scss
- ui/src/components/Entity/EntityToolbar.jsx
- ui/src/components/Entity/EntityToolbar.scss
- ui/src/components/Facet/SearchFacet.jsx
- ui/src/components/Toolbar/DownloadButton.jsx
- ui/src/components/common/CheckboxList.jsx
- ui/src/components/common/CheckboxList.scss
- ui/src/components/common/DualPane.scss
- ui/src/components/common/Role.jsx
- ui/src/screens/DiagramScreen/DiagramScreen.jsx
Fixes for:
- Content pane horizontal overflow issue
- Entity preview and search facet icon issue
- Diagram editor title and description
- Document upload placeholder css
> Small UI Fixes: overflow, icons +

- ui/src/components/Toolbar/PagingButtons.jsx
- ui/src/viewers/PdfViewer.jsx
- ui/src/viewers/PdfViewerPage.jsx
> PDFViewer: text view paging buttons fix

- aleph/oauth.py
- aleph/settings.py
- aleph/signals.py
- aleph/views/sessions_api.py
- setup.py
This should make it easier to select and add OAuth/OIDC handlers.
> Select OAuth login handler using Python entry point

- ui/src/components/MappingEditor/MappingSplitSection.scss
Hey @kjacks I found a missing commit in the branches -- should we merge that.
> Layout fix on mapping editor

- aleph/authz.py
- aleph/settings.py
- aleph/views/base_api.py
- aleph/views/collections_api.py
- aleph/views/context.py
- aleph/views/sessions_api.py
- aleph/views/status_api.py
- requirements-toolkit.txt
- services/ingest-file/requirements.txt
Current plan is to limit anonymous users who overly stress the API by rejecting their requests with an HTTP error.
> API rate limiting

- aleph/index/collections.py
- aleph/views/base_api.py
- aleph/views/reconcile_api.py
- ui/src/components/Collection/CollectionOverviewMode.jsx
- ui/src/components/Collection/CollectionStatistics.jsx
> Include intervals in statistics API

- ui/package.json
- ui/src/components/common/Property.jsx
> Support entity links as property values

- ui/src/screens/PagesScreen/PagesScreen.scss
@pudo Just ended up making a few little changes - but feel free to take them or leave it as is! :)
> Pages Screen Styling

- ui/package.json
- ui/src/components/Collection/CollectionViews.jsx
- ui/src/components/CollectionIndex/CollectionIndexItem.jsx
- ui/src/components/Dashboard/Dashboard.jsx
- ui/src/components/Dashboard/Dashboard.scss
- ui/src/components/Entity/EntityActionBar.jsx
- ui/src/components/Entity/EntityListManager.jsx
- ui/src/components/Entity/EntityViews.jsx
- ui/src/components/common/Count.jsx
- ui/src/components/common/Count.scss
- ui/src/components/common/ResultCount.jsx
- ui/src/components/common/ResultText.jsx
- ui/src/components/common/index.jsx
- ui/src/screens/CollectionIndexScreen/CollectionIndexScreen.jsx
- ui/src/screens/SearchScreen/SearchScreen.jsx
> Count badges

- ui/src/app/App.scss
- ui/src/components/Entity/EntityListManager.jsx
- ui/src/components/Notification/Notification.scss
- ui/src/components/common/Diagram.jsx
- ui/src/dialogs/AddToDiagramDialog/AddToDiagramDialog.jsx
- ui/src/dialogs/AddToDiagramDialog/AddToDiagramDialog.scss
> WIP: Mini UI Fixes

- aleph/logic/entities.py
- aleph/tests/test_diagrams_api.py
- aleph/views/entities_api.py
- requirements.txt
- services/ingest-file/requirements.txt
- ui/package.json
Super weird, but I can't think of another option short of building joins into ES.
> Inline names of referenced entities.

- ui/src/dialogs/EntityDeleteDialog/EntityDeleteDialog.jsx
- ui/src/dialogs/EntityDeleteDialog/EntityDeleteDialog.scss
Fixes #1238 
Also added some progress reporting as it's deleting...
> converted entity delete processing to sequential instead of parallel

- aleph/queues.py
- aleph/settings.py
- docker-compose.dev.yml
- services/translate/Dockerfile
- services/translate/README.md
- services/translate/setup.py
- services/translate/translate/cli.py
- services/translate/translate/worker.py
Fixes #1252 - documentation is happening here: https://docs.alephdata.org/developers/technical-faq/adding-text-processors
> NLP pipeline example

- ui/package.json
- ui/src/components/Entity/EntityListManager.jsx
- ui/src/queries.js
@pudo This is basically ready to go :), but I'd like to test it a bit more and perhaps tweak a couple minor things before merging.  
The one question I had was whether to include property links in addition to schema edges as possible options in the edge create dialog.  They are included by default, and it's working to create them, but I can remove them if you feel like it might be too confusing
> Create edge from entity list manager

- site/aleph.occrp.org/pages/help.en.md
- ui/package.json
- ui/src/components/Collection/CollectionInfo.scss
- ui/src/components/CollectionIndex/CollectionIndexItem.scss
- ui/src/components/Entity/EntityPreview.scss
- ui/src/components/Notification/Notification.scss
- ui/src/components/common/Breadcrumbs.scss
- ui/src/screens/SettingsScreen/SettingsScreen.jsx
- ui/src/screens/SettingsScreen/SettingsScreen.scss
Small ui fixes (see commits) + latest react-ftm
> More UI Fixes

- ui/src/components/Document/DocumentViewMode.jsx
- ui/src/viewers/AudioViewer.jsx
- ui/src/viewers/AudioViewer.scss
- ui/src/viewers/VideoViewer.jsx
Resolves #1335 
Tested in: Chrome, Firefox, and Safari latest
> Media Viewers

- ui/src/actions/configActions.js
- ui/src/actions/index.js
- ui/src/components/Toolbar/DownloadButton.jsx
- ui/src/components/Toolbar/DownloadButton.scss
- ui/src/reducers/config.js
> Download warning for source documents

- ui/src/components/Dashboard/Dashboard.jsx
- ui/src/components/Dashboard/Dashboard.scss
- ui/src/components/common/Breadcrumbs.jsx
- ui/src/components/common/Breadcrumbs.scss
- ui/src/components/common/DualPane.jsx
- ui/src/components/common/DualPane.scss
- ui/src/screens/SearchScreen/SearchScreen.jsx
- ui/src/screens/SearchScreen/SearchScreen.scss
Solves issue with search results scrolling on Safari
> Safari flex container height fixes

- ui/src/components/MappingEditor/MappingKeyAssign.jsx
- ui/src/components/MappingEditor/MappingLabel.jsx
- ui/src/components/MappingEditor/MappingList.js
- added required entity type props to entity select
- added key_literal to generated query for interval type schemata
- adjusted mapping validation for interval types
> Mapping Editor Fixes

- ui/package.json
- ui/src/components/EntityTable/EntityTable.jsx
Support for row multi-select and key scrolling
> Table editor updates

- ui/src/components/EntitySet/EntitySetIndex.jsx
- ui/src/components/Notification/NotificationList.jsx
- ui/src/components/Screen/ErrorScreen.jsx
- ui/src/components/Screen/LoadingScreen.jsx
- ui/src/screens/EntitySetIndexScreen/EntitySetIndexScreen.jsx
- ui/src/screens/GroupScreen/GroupScreen.jsx
- ui/src/screens/NotificationsScreen/NotificationsScreen.jsx
Resolves #1448  
Issue wasn't with hotkeys in the end, but with the requireSession param not being passed through the loading screen
> Ensure auth is forced when trying to access session-required screens

- ui/src/reducers/entitySets.js
> Ensure objectLoadError is passed entity set id on request error

- ui/src/dialogs/DocumentUploadDialog/DocumentUploadDialog.jsx
run max 10 file upload requests in parallel. Should fix #1489
> Upload: limit concurrency

- ui/src/components/EntityTable/EntityTable.jsx
> Modified table editor waypoint offset

- ui/src/app/variables.scss
- ui/src/components/AuthButtons/AuthButtons.jsx
- ui/src/components/AuthButtons/AuthButtons.scss
- ui/src/components/EntityTable/EntityTable.jsx
- ui/src/components/Navbar/Navbar.scss
- Render skeleton instead of "Sign in" while role isPending
- Improved navbar smaller screen crowding a bit
- Prevent app title from wrapping lines
> UI: Navbar tweaks

- aleph/search/__init__.py
- aleph/views/xref_api.py
- ui/src/components/Collection/CollectionXrefMode.jsx
- ui/src/components/Collection/CollectionXrefMode.scss
This PR adds xref party mode which jumbles up the xref to include a healthy mix of good/bad results. This is going to be useful in creating training data for our xref models.
> Xref Party Mode

- ui/package.json
- ui/src/actions/entitySetActions.js
- ui/src/actions/index.js
- ui/src/components/Diagram/DiagramEditor.jsx
- ui/src/components/Entity/entityEditorWrapper.jsx
- ui/src/components/EntitySet/EntitySetManageMenu.jsx
- ui/src/components/common/ClipboardInput.jsx
- ui/src/dialogs/DiagramExportDialog/DiagramExportDialog.jsx
- ui/src/dialogs/DiagramExportDialog/DiagramExportDialog.scss
- ui/src/screens/DiagramScreen/DiagramScreen.jsx
Moves svg, ftm, and embed export options into a single menu
@pudo I wasn't sure on the wording for the ui explanations on some of this, so feel free to suggest any edits :)
> Support Diagram Embeds in the UI

- ui/src/components/Investigation/InvestigationQuickLinks.jsx
- ui/src/components/common/LandingQuickLinks.jsx
- ui/src/components/common/QuickLinks.jsx
- ui/src/components/common/QuickLinks.scss
- ui/src/components/common/index.jsx
- ui/src/screens/NotificationsScreen/NotificationsScreen.jsx
- ui/src/screens/NotificationsScreen/NotificationsScreen.scss
> Landing Quick Links

- ui/src/components/Collection/CollectionDateHistogram.jsx
- ui/src/components/Collection/CollectionStatisticsGroup.jsx
- ui/src/components/Collection/CollectionStatisticsGroup.scss
- ui/src/components/EntitySearch/FacetedEntitySearch.scss
- ui/src/components/Facet/DateFacet.scss
> Collection Date Histogram

- aleph/manage.py
This PR adds a `dump-profiles` CLI so that we can backup profiles to more easily run our machine learning wizardry.
> Dump Profiles CLI

- docker-compose.dev.yml
- docker-compose.yml
Resolves issue with synonyms not working correctly with chinese, japanese, or korean characters
> Bump the version of the aleph-elasticsearch library we use

- aleph/model/document.py
- aleph/validation/schema/ingest.yml
Some of the existing fields were not being used; fix those as well. Fixes https://github.com/alephdata/aleph/issues/1831
> Add a new document metadata field to store the publisher of a document

- ui/src/components/AuthButtons/AuthButtons.jsx
- ui/src/components/Collection/CollectionInfo.jsx
- ui/src/components/common/Role.scss
- ui/src/dialogs/CollectionAccessDialog/CollectionAccessDialog.scss
> Handle long role names

- ui/src/app/Router.jsx
- ui/src/screens/EntitySetScreen/EntitySetScreen.jsx
> Abstract Entity Set Routing

- aleph/search/facet.py
- aleph/search/result.py
- aleph/tests/test_base_api.py
- aleph/tests/test_search_api.py
- aleph/tests/test_stream_api.py
- aleph/tests/util.py
- ui/src/components/EntitySearch/FacetedEntitySearch.jsx
- ui/src/components/SearchField/SearchFieldSelect.jsx
> Use the caption of entities as label for facet values

- ui/src/components/EntitySearch/FacetedEntitySearch.jsx
- ui/src/components/SearchField/SearchFieldSelect.jsx
> Filter out text properties from custom search facet select

- site/aleph.occrp.org/pages/about.en.md
Hi, this is an updated about page to which I added a second form to have separate applications for FOO and BAR, as discussed.
> Aboutpage updates

- ui/src/components/Collection/CollectionReference.jsx
> Display collection foreign id with clipboard input

- ui/src/components/Entity/EntityViews.jsx
- ui/src/components/Entity/EntityViews.scss
> Show warning when table is part of a larger workbook

- site/aleph.occrp.org/pages/about.en.md
Update the Aleph about page to use the new form for FOO/BAR requests
> update about page w/ new form link

- contrib/aleph-traefik-minio-keycloak/.dockerignore
- contrib/aleph-traefik-minio-keycloak/.gitignore
- contrib/aleph-traefik-minio-keycloak/LICENSE.txt
- contrib/aleph-traefik-minio-keycloak/README.rst
- contrib/aleph-traefik-minio-keycloak/docker-compose.yml
- contrib/aleph-traefik-minio-keycloak/start.sh
- contrib/aleph-traefik-minio-keycloak/stop.sh
- contrib/aleph-traefik-minio-keycloak/traefik.toml
- contrib/aleph-traefik-minio-keycloak/traefik_dynamic.toml
This is my sample config for aleph using traefik, keycloak and minio.
> Add config file examples for traefik/keycloak/minio setup

- aleph/__init__.py
- requirements.txt
ref: https://github.com/alephdata/aleph/pull/2012,  https://github.com/alephdata/aleph/runs/7017987373?check_suite_focus=true
> Fix pyyaml 6.0 build

- aleph/tests/test_serializers.py
- aleph/views/serializers.py
ref: https://github.com/alephdata/aleph/issues/2327 and https://github.com/alephdata/aleph/pull/2328
> Raise a 500 error when we're expecting results but the results array is empty

- aleph/tests/test_serializers.py
- aleph/views/serializers.py
fixes https://github.com/alephdata/aleph/issues/2370
> Don't return a 500 response in cases where empty result is expected

- aleph/pages/home.en.md
- site/aleph.occrp.org/pages/home.en.md
On the home page, show a message that public access is currently disabled.
> Show message that public access is disabled

- site/aleph.occrp.org/pages/home.en.md
... after re-enabling public access
> Remove the public access disabled message

- Makefile
- aleph.env.tmpl
- aleph/__init__.py
- aleph/core.py
- aleph/logic/collections.py
- aleph/logic/documents.py
- aleph/logic/processing.py
- aleph/manage.py
- aleph/queues.py
- aleph/settings.py
- aleph/tests/test_ingest_api.py
- aleph/tests/test_xref.py
- aleph/tests/test_xref_api.py
- aleph/tests/util.py
- aleph/util.py
- aleph/views/status_api.py
- aleph/views/util.py
- aleph/worker.py
- contrib/test.sh
- docker-compose.dev.yml
- docker-compose.yml
- helm/charts/aleph/templates/aleph-upgrade-job.yaml
- helm/charts/aleph/templates/api.yaml
- helm/charts/aleph/templates/ingest-file.yaml
- helm/charts/aleph/templates/worker.yaml
- helm/charts/aleph/values.yaml
- requirements.txt
- ui/src/screens/SystemStatusScreen/SystemStatusScreen.jsx
... to make develop branch stable enough to deploy from. RabbitMQ changes live in a separate branch in https://github.com/alephdata/aleph/tree/sunu/rabbitmq-wip until they are stable enough to deploy again.
> Rollback RabitMQ based task queue changes

- aleph/settings.py
Fixes a bug where we were setting unwanted env vars the settings object
> don't set env var prefix name as flask config setting

- .github/dependabot.yml
> Keep GitHub Actions up to date

- ui/src/components/Investigation/InvestigationSidebar.scss
- ui/src/screens/InvestigationScreen/InvestigationScreen.scss
Closes #2638.
**Before:**
https://user-images.githubusercontent.com/1512805/200297248-dc39b10e-c492-4061-8fb8-28ee36397f3a.mov
**After:**
https://user-images.githubusercontent.com/1512805/200297315-003499ba-380d-4166-8258-639097ead197.mov
> Fix investigations sidebar width

- aleph/views/base_api.py
- ui/src/components/common/AppItem.jsx
I accidentally implemented  #2742 while looking at how one would do that.
> Show FTM version on about page

- ui/package.json
- ui/src/app/legacyRedirects.tsx
- ui/src/components/common/AppItem.jsx
I make this same, basic mistake over and over again even though I should know better, so I’ve also enabled a linter rule that will fail builds when I make this mistake again in the future.
> Fix missing key props (and at linter rule to prevent this from happening again)

- contrib/aleph-traefik-minio-keycloak/docker-compose.yml
- contrib/keycloak/docker-compose.dev-keycloak.yml
- docker-compose.dev.yml
- docker-compose.yml
- helm/charts/aleph/values.yaml
Bump `ingest-file` to the latest RC to test the fix for https://github.com/alephdata/ingest-file/issues/398
> ingest-file 3.18.0 rc4

- ui/src/selectors.js
> Fix app banner

- docker-compose.dev.yml
See https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-2-0.
> Remove deprecated --eager-loading parameter

- aleph/migrate/versions/4c9e198c5b31_entitysets.py
- aleph/migrate/versions/9dcef7592cea_added_fields_to_entitysetitem_to_support_profiles.py
- aleph/migrate/versions/aa486b9e627e_hard_deletes.py
- aleph/migrate/versions/b3959bf8cc66_entity_ids.py
> Update migrations to SQLAlchemy 2.x

- ui/src/app/Router.jsx
- ui/src/components/AuthButtons/AuthButtons.jsx
- ui/src/components/Investigation/InvestigationSidebar.jsx
- ui/src/components/Timeline/Timeline.tsx
- ui/src/components/Timeline/TimelineActions.tsx
- ui/src/components/common/Breadcrumbs.jsx
- ui/src/components/common/RelativeTime.jsx
- ui/src/react-ftm/editors/EntitySelect.tsx
- ui/src/react-ftm/utils/validate.ts
This fixes a few trivial eslint warnings (unused imports, missing export names, …).
> Fix linting issues

- aleph/logic/alerts.py
Saw that the build failed for my PR. After looking into why, i discovered `make
format`.
I'll add the `black` formatter as a plugin to my editor so we don't have to go
through this again.
> discover `make format`, run that

- contrib/aleph-traefik-minio-keycloak/docker-compose.yml
- contrib/keycloak/docker-compose.dev-keycloak.yml
- docker-compose.dev.yml
- docker-compose.yml
> Bump the version of ingest-file used in docker-compose

- ui/src/dialogs/DocumentUploadDialog/DocumentUploadForm.jsx
Relates to #3403 (first step measure)
> Suggest alephclient for uploading lots of files instead of UI

- docs/src/pages/developers/installation.mdx
> Add worker scaling docs

- aleph.env.tmpl
- helm/charts/aleph/values.yaml
> Explicitly disable servicelayer worker threads in Helm chart & env

- .gitignore
- aleph/tests/test_settings.py
This test was `.gitignore`'d on PR #2538. This fixes that.
> added ignored settings test

- docs/src/pages/developers/memorious.mdx
> docs: update memorious link

- Makefile
Fixes a problem introduced in #3687
> Add playwright version build arg to run step

- .github/workflows/docs.yml
- docs/src/pages/developers/technical-faq/index.mdx
- fixes a broken link from #3681
- enables running the docs workflow when PRs make changes to docs
> Fix broken link in docs

- docs/src/pages/developers/installation.mdx
refer to alephdata/aleph/raw/ to get actual files
> download actual files instead of HTML wrapped configuration

- docs/src/pages/developers/installation.mdx
"shell aleph upgrade" is mandatory for 1st time installs.
> Order of commands made more clean

- .github/workflows/build.yml
- .github/workflows/e2e.yml
- Makefile
Cherry picking 5bd1c00 and e824bb3 from release/4.0.0.
> Fix docker compose command

- ui/src/screens/SystemStatusScreen/SystemStatusScreen.jsx
* Previously, only the time was displayed if the start time/last update was on the same day. This could be confusing, so we now display "today" in these cases.
* The default US English short date format is `MM/DD/YY` which can be confusing, especially for users outside the US. I've replace this with a less ambiguous date format: Aug 5, 2024.
> Improve date formats on status page

- aleph/manage.py
- aleph/tests/test_manage.py
> Show the Aleph version when using the -v or --version options

- ui/package-lock.json
- ui/package.json
- ui/src/app/api.js
Manually updating some dependencies that Dependabot couldn’t properly rebase.
> Misc dependency updates
